### ISSUE TITLE
LSP sometimes working with Metals, sometimes spamming “the request has been cancelled”

### ISSUE THREAD

**Issue by Kazark** [emacs-lsp/lsp-mode#1323]
**Describe the bug**
I have [Spacemacs configured to use Metals](https://github.com/syl20bnr/spacemacs/issues/12462) as an LSP backend for Scala development, i.e. my `dotspacemacs-configuration-layers` includes:

```lisp
     (scala :variables
            scala-backend 'scala-metals
            scala-enable-eldoc t
            scala-use-unicode-arrows t
            scala-auto-start-backend t)
```

Sometimes I open a file, and everything works well. I get a rich development experience backed by whatever capabilities Metals exposes via LSP. Other times I open it up and it seems that nothing is working, and in the `*Messages*` buffer I see the likes of:

```
LSP :: Connected to [metals:38879 status:starting].
LSP :: metals:38879 initialized successfully
LSP :: The request (id: 2, method: 'textDocument/hover') has been cancelled
LSP :: The request (id: 4, method: 'textDocument/hover') has been cancelled
LSP :: The request (id: 6, method: 'textDocument/hover') has been cancelled
LSP :: The request (id: 9, method: 'textDocument/hover') has been cancelled
LSP :: The request (id: 11, method: 'textDocument/hover') has been cancelled
```

As I navigate around the Scala file, that message just spams again and again.

I'm on a Mac running Metals 0.8.0 (though this was also happening on the previous version) with Bloop 1.4.0-RC1 running as a service install installed by `brew services start scalacenter/bloop/bloop`. I've tried restarting Bloop and it doesn't fix it. I also haven't been able to figure out why it sometimes works, and other times does not.

Of course it is acceptable for requests to get occasionally cancelled, but this seems to be in some genuinely dysfunctional state. My autocompletion is also not working but I am not sure if this is a related problem or is something else.

**To Reproduce**
Ways I have not been able to reproduce:
* I was not able to reproduce with the `emacs -q -l lsp-start-plain.el` technique because I am not good with bare-bones Emacs (being an Evil/Spacemacs guy, and not really grokking Emacs as such) and it did not have Scala support enabled. 
* I have not yet tried to reproduce in the Docker image. I saw three configuration differences with my machine versus the Docker image [w.r.t. Scala](https://github.com/emacs-lsp/lsp-docker/blob/master/docker/Dockerfile#L85): that is Linux, mine is Mac; that uses Metals 0.7.0, I am using Metals 0.8.0 (though I had the same problem on 0.7.6); that does not have a separately-installed Bloop, and I installed my Bloop with Homebrew.
Please advice if you want me to proceed further with either of these methods. **I will work on reproducing this with an open-source Scala repo on my machine at least, as a starting point, and will report back.**

**Expected behavior**
The requests can be cancelled if one is taking super long or if I move off an identifier but when I focus on an identifier and wait I should get a popup.

**Which Language Server did you use**
Metals 0.8.0 (Scala).

**OS**
```
> uname -a
Darwin My-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
```

**Error callstack**

There is no actual error, only warnings, but the LSP workspace log (fresh one compared to what I posted on Reddit) is:

```
[Trace - 09:29:16 AM] Sending request 'textDocument/hover - (15)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 172,
    "character": 2
  }
}


[Trace - 09:29:16 AM] Sending request 'textDocument/documentHighlight - (16)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 172,
    "character": 2
  }
}


[Trace - 09:29:16 AM] Received response 'textDocument/documentHighlight - (16)' in 11ms.
Result: []


[Trace - 09:29:19 AM] Sending request 'textDocument/hover - (17)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 173,
    "character": 2
  }
}


[Trace - 09:29:19 AM] Sending request 'textDocument/documentHighlight - (18)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 173,
    "character": 2
  }
}


[Trace - 09:29:19 AM] Received response 'textDocument/documentHighlight - (18)' in 11ms.
Result: []


[Trace - 09:29:19 AM] Sending request 'textDocument/hover - (19)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 173,
    "character": 10
  }
}


[Trace - 09:29:19 AM] Sending request 'textDocument/hover - (20)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 173,
    "character": 14
  }
}


[Trace - 09:29:19 AM] Sending request 'textDocument/documentHighlight - (21)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 173,
    "character": 14
  }
}


[Trace - 09:29:19 AM] Sending notification '$/cancelRequest'.
Params: {
  "id": 21
}


[Trace - 09:29:19 AM] Sending request 'textDocument/documentHighlight - (22)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 173,
    "character": 14
  }
}


[Trace - 09:29:19 AM] Received response 'nil - (21)' in 0ms.
Result: null


[Trace - 09:29:19 AM] Received response 'textDocument/documentHighlight - (22)' in 11ms.
Result: []


[Trace - 09:29:20 AM] Sending request 'textDocument/hover - (23)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 173,
    "character": 14
  }
}


[Trace - 09:29:21 AM] Sending request 'textDocument/hover - (24)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 172,
    "character": 14
  }
}


[Trace - 09:29:22 AM] Received response 'textDocument/hover - (3)' in 176ms.
Result: null


[Trace - 09:29:22 AM] Sending request 'textDocument/hover - (25)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 170,
    "character": 4
  }
}


[Trace - 09:29:22 AM] Received response 'textDocument/hover - (4)' in 44ms.
Result: null


[Trace - 09:29:22 AM] Received response 'textDocument/hover - (5)' in 33ms.
Result: null


[Trace - 09:29:22 AM] Sending request 'textDocument/hover - (26)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 169,
    "character": 8
  }
}


[Trace - 09:29:22 AM] Received response 'textDocument/hover - (6)' in 26ms.
Result: null


[Trace - 09:29:22 AM] Sending request 'textDocument/hover - (27)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 168,
    "character": 14
  }
}


[Trace - 09:29:23 AM] Received response 'textDocument/hover - (7)' in 8ms.
Result: null


[Trace - 09:29:23 AM] Received response 'textDocument/hover - (8)' in 18ms.
Result: null


[Trace - 09:29:26 AM] Sending request 'textDocument/hover - (28)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 168,
    "character": 17
  }
}


[Trace - 09:29:26 AM] Sending request 'textDocument/hover - (29)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 168,
    "character": 20
  }
}


[Trace - 09:29:26 AM] Sending request 'textDocument/hover - (30)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 168,
    "character": 28
  }
}


[Trace - 09:29:27 AM] Sending request 'textDocument/hover - (31)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 168,
    "character": 29
  }
}


[Trace - 09:29:27 AM] Sending request 'textDocument/documentHighlight - (32)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 168,
    "character": 29
  }
}


[Trace - 09:29:27 AM] Sending notification '$/cancelRequest'.
Params: {
  "id": 32
}


[Trace - 09:29:27 AM] Sending request 'textDocument/documentHighlight - (33)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 168,
    "character": 29
  }
}


[Trace - 09:29:27 AM] Sending notification '$/cancelRequest'.
Params: {
  "id": 33
}


[Trace - 09:29:27 AM] Sending request 'textDocument/documentHighlight - (34)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 168,
    "character": 29
  }
}


[Trace - 09:29:27 AM] Sending notification '$/cancelRequest'.
Params: {
  "id": 34
}


[Trace - 09:29:27 AM] Sending request 'textDocument/documentHighlight - (35)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 168,
    "character": 29
  }
}


[Trace - 09:29:27 AM] Received response 'nil - (32)' in 0ms.
Result: []


[Trace - 09:29:27 AM] Received response 'nil - (33)' in 0ms.
Result: []


[Trace - 09:29:27 AM] Received response 'nil - (34)' in 0ms.
Result: null


[Trace - 09:29:27 AM] Received response 'textDocument/documentHighlight - (35)' in 11ms.
Result: []


[Trace - 09:29:27 AM] Sending notification '$/cancelRequest'.
Params: {
  "id": 23
}


[Trace - 09:29:27 AM] Sending request 'textDocument/hover - (36)'.
Params: {
  "textDocument": {
    "uri": "<redacted>.scala"
  },
  "position": {
    "line": 168,
    "character": 29
  }
}


[Trace - 09:29:27 AM] Received response 'nil - (23)' in 0ms.
Result: null


[Trace - 09:29:36 AM] Received response 'textDocument/hover - (15)' in 8ms.
Result: null


[Trace - 09:29:39 AM] Received response 'textDocument/hover - (17)' in 305ms.
Result: null


[Trace - 09:29:39 AM] Received response 'textDocument/hover - (19)' in 5ms.
Result: null


[Trace - 09:29:39 AM] Received response 'textDocument/hover - (20)' in 7ms.
Result: null


[Trace - 09:29:41 AM] Received response 'textDocument/hover - (24)' in 32ms.
Result: null


[Trace - 09:29:42 AM] Received response 'textDocument/hover - (25)' in 3ms.
Result: null


[Trace - 09:29:42 AM] Received response 'textDocument/hover - (26)' in 5ms.
Result: null


[Trace - 09:29:42 AM] Received response 'textDocument/hover - (27)' in 4ms.
Result: null


[Trace - 09:29:46 AM] Received response 'textDocument/hover - (28)' in 4ms.
Result: null


[Trace - 09:29:46 AM] Received response 'textDocument/hover - (29)' in 4ms.
Result: null


[Trace - 09:29:46 AM] Received response 'textDocument/hover - (30)' in 5ms.
Result: null


[Trace - 09:29:47 AM] Received response 'textDocument/hover - (31)' in 6ms.
Result: null


[Trace - 09:29:47 AM] Received response 'textDocument/hover - (36)' in 6ms.
Result: null
```

**Links**

Previously posted on [StackOverflow](https://emacs.stackexchange.com/q/54923/19069) and [Reddit](https://www.reddit.com/r/spacemacs/comments/eorwbt/lsp_sometimes_working_with_metals_sometimes/?utm_source=share&utm_medium=web2x).

**Comment by yyoncho** [comment]
Thank you for detailed bug report. I will follow up with instructions how to collect some more debug data.

**Comment by Kazark** [comment]
I'm going to see if I can reproduce on [http4s](https://github.com/http4s/http4s) as a step towards being able to give you reproduction steps.

**Comment by kurnevsky** [comment]
Did you try to reimport the project with `lsp-metals-build-import`?

Also you can check `project_dir/.metals/metals.log` for errors.

**Comment by Kazark** [comment]
@kurnevsky thanks. Will try both of those things. I've tried a bunch of things and can't keep track of what so I'm not going to say I have tried `lsp-metals-build-import` until I've tried it again (because I think I have, but I'd like to do a distinct experiment).

**Comment by Kazark** [comment]
Yep, after a fresh `lsp-metals-build-import`, still getting the same behavior.

**Comment by Kazark** [comment]
@kurnevsky Ah, `metals.log`! Full of errors! Here is a (redacted) copy of the log from my latest session:

```
INFO  running installed 'bloop bsp --protocol local --socket /var/folders/8l/lmk_c8ps2bggqkxvmphwxhtc0000gn/T/bsp2826756088973153477/-148q2qohp726k.socket'
INFO  The server is listening for incoming connections at local:///var/folders/8l/lmk_c8ps2bggqkxvmphwxhtc0000gn/T/bsp2826756088973153477/-148q2qohp726k.socket...
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/<redacted>/Library/Caches/org.scalameta.metals/bsp.trace.json
INFO  Accepted incoming BSP client connection at local:///var/folders/8l/lmk_c8ps2bggqkxvmphwxhtc0000gn/T/bsp2826756088973153477/-148q2qohp726k.socket
INFO  request received: build/initialize
INFO  time: connected to build server in 0.21s
INFO  BSP initialization handshake complete.
INFO  time: indexed workspace in 5.07s
ERROR [0m[32m[D][0m Computing sources and classpath hashes for <redacted>
ERROR [0m[32m[D][0m Scheduling compilation for <redacted>...
ERROR [0m[32m[D][0m Using successful result for <redacted> associated with /Users/<redacted>/src/<redacted>/.bloop/<redacted>/scala-2.11/bloop-internal-classes/classes-Metals-plPpQmc9R6S6qNnSt3WOng==-vjUJljA8S-STslAweP-6DA==
ERROR [0m[32m[D][0m Increasing counter for /Users/<redacted>/src/<redacted>/.bloop/<redacted>/scala-2.11/bloop-internal-classes/classes-Metals-plPpQmc9R6S6qNnSt3WOng==-vjUJljA8S-STslAweP-6DA== to 4
ERROR [0m[32m[D][0m Disabled compiler plugin classloading, unsupported in 2.11.
ERROR [0m[32m[D][0m External classes directory /Users/<redacted>/src/<redacted>/.bloop/<redacted>/bloop-bsp-clients-classes/classes-Metals-vTJZl0ylTsyyB_X19IM99Q==
ERROR [0m[32m[D][0m Read-only classes directory /Users/<redacted>/src/<redacted>/.bloop/<redacted>/scala-2.11/bloop-internal-classes/classes-Metals-plPpQmc9R6S6qNnSt3WOng==-vjUJljA8S-STslAweP-6DA==
ERROR [0m[32m[D][0m New rw classes directory /Users/<redacted>/src/<redacted>/.bloop/<redacted>/bloop-internal-classes/classes-Metals-vTJZl0ylTsyyB_X19IM99Q==-nFHxT8biRVWdk6Mwf6yylw==
Exception in thread "pool-26-thread-1" java.lang.NoClassDefFoundError: javax/tools/DiagnosticListener
	at scala.tools.util.PathResolverBase$Calculated$.javaBootClasspath(PathResolver.scala:277)
	at scala.tools.util.PathResolverBase$Calculated$.basis(PathResolver.scala:283)
	at scala.tools.util.PathResolverBase$Calculated$.containers$lzycompute(PathResolver.scala:293)
	at scala.tools.util.PathResolverBase$Calculated$.containers(PathResolver.scala:293)
	at scala.tools.util.PathResolverBase.containers(PathResolver.scala:309)
	at scala.tools.util.PathResolver.computeResult(PathResolver.scala:341)
	at scala.tools.util.PathResolver.computeResult(PathResolver.scala:332)
	at scala.tools.util.PathResolverBase.result(PathResolver.scala:314)
	at scala.tools.nsc.backend.JavaPlatform$class.classPath(JavaPlatform.scala:28)
	at scala.tools.nsc.Global$GlobalPlatform.classPath(Global.scala:115)
	at scala.tools.nsc.Global.scala$tools$nsc$Global$$recursiveClassPath(Global.scala:131)
	at scala.tools.nsc.Global$GlobalMirror.rootLoader(Global.scala:64)
	at scala.reflect.internal.Mirrors$Roots$RootClass.<init>(Mirrors.scala:307)
	at scala.reflect.internal.Mirrors$Roots.RootClass$lzycompute(Mirrors.scala:321)
	at scala.reflect.internal.Mirrors$Roots.RootClass(Mirrors.scala:321)
	at scala.reflect.internal.Mirrors$Roots$EmptyPackageClass.<init>(Mirrors.scala:330)
	at scala.reflect.internal.Mirrors$Roots.EmptyPackageClass$lzycompute(Mirrors.scala:336)
	at scala.reflect.internal.Mirrors$Roots.EmptyPackageClass(Mirrors.scala:336)
	at scala.reflect.internal.Mirrors$Roots.EmptyPackageClass(Mirrors.scala:276)
	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:250)
	at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:73)
	at scala.tools.nsc.Global.rootMirror(Global.scala:71)
	at scala.tools.nsc.Global.rootMirror(Global.scala:39)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1390)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1242)
	at scala.tools.nsc.interactive.Global$TyperRun.<init>(Global.scala:1321)
	at scala.tools.nsc.interactive.Global.newTyperRun(Global.scala:1344)
	at scala.tools.nsc.interactive.Global.<init>(Global.scala:299)
	at scala.meta.internal.pc.MetalsGlobal.<init>(MetalsGlobal.scala:29)
	at scala.meta.internal.pc.ScalaPresentationCompiler.newCompiler(ScalaPresentationCompiler.scala:168)
	at scala.meta.internal.pc.ScalaPresentationCompiler$$anonfun$1.apply(ScalaPresentationCompiler.scala:57)
	at scala.meta.internal.pc.ScalaPresentationCompiler$$anonfun$1.apply(ScalaPresentationCompiler.scala:57)
	at scala.meta.internal.pc.CompilerAccess.loadCompiler(CompilerAccess.scala:36)
	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:120)
	at scala.meta.internal.pc.CompilerAccess$$anonfun$withNonInterruptableCompiler$1.apply(CompilerAccess.scala:110)
	at scala.meta.internal.pc.CompilerAccess$$anonfun$onCompilerJobQueue$1.apply$mcV$sp(CompilerAccess.scala:198)
	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:73)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.ClassNotFoundException: javax.tools.DiagnosticListener
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 42 more
ERROR [0m[32m[D][0m Full compilation, no sources in previous analysis.
ERROR [0m[32m[D][0m All sources are invalidated.
ERROR [0m[32m[D][0m Initial set of included nodes: 
ERROR [0m[32m[D][0m Recompiling all sources: number of invalidated sources > 50.0% of all sources
ERROR [0m[32m[D][0m Returning already retrieved and compiled bridge: /Users/<redacted>/Library/Caches/bloop/components/ch.epfl.scala-compiler-bridge_2.11-1.3.0-M4+32-b1accb96-bin_2.11.12__52.0/ch.epfl.scala-compiler-bridge_2.11-1.3.0-M4+32-b1accb96-bin_2.11.12__52.0.jar.
INFO  compiling <redacted> (22 scala sources)
ERROR [0m[32m[D][0m Returning already retrieved and compiled bridge: /Users/<redacted>/Library/Caches/bloop/components/ch.epfl.scala-compiler-bridge_2.11-1.3.0-M4+32-b1accb96-bin_2.11.12__52.0/ch.epfl.scala-compiler-bridge_2.11-1.3.0-M4+32-b1accb96-bin_2.11.12__52.0.jar.
ERROR [0m[32m[D][0m [zinc] Running cached compiler 914f90d for Scala compiler version 2.11.12
ERROR [0m[32m[D][0m [zinc] The Scala compiler is invoked with:
ERROR 	-deprecation
ERROR 	-feature
ERROR 	-language:postfixOps
ERROR 	-Xlint
ERROR 	-Xlog-free-terms
ERROR 	-Xlog-free-types
ERROR 	-language:implicitConversions
ERROR 	-language:higherKinds
ERROR 	-language:existentials
ERROR 	-language:postfixOps
ERROR 	-Ywarn-dead-code
ERROR 	-Ywarn-numeric-widen
ERROR 	-Ywarn-inaccessible
ERROR 	-unchecked
ERROR 	-nowarn
ERROR 	-Xplugin-require:macroparadise
ERROR 	-P:semanticdb:synthetics:on
ERROR 	-P:semanticdb:failures:warning
ERROR 	-P:semanticdb:sourceroot:/Users/<redacted>/src/<redacted>
ERROR 	-Yrangepos
ERROR 	-Xplugin-require:semanticdb
ERROR 	-Xplugin:/Users/<redacted>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/wartremover/wartremover_2.11/2.2.1/wartremover_2.11-2.2.1.jar
ERROR 	-Xplugin:/Users/<redacted>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.11.12/4.2.3/semanticdb-scalac_2.11.12-4.2.3.jar
ERROR 	-Xplugin:/Users/<redacted>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scalamacros/paradise_2.11.12/2.1.1/paradise_2.11.12-2.1.1.jar
ERROR 	-bootclasspath
ERROR 	/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/classes:/Users/<redacted>/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar
ERROR 	-classpath
ERROR 	<redacted>
```

Should I open an issue with Metals, I suppose?

**Comment by yyoncho** [comment]
I think that it is caused by a bug in lsp-mode which triggers multiple time on idle event probably when you have multiple files open at the same time. Can you do the following `M-x trace-function RET lsp--on-idle RET` and observe the trace output?

**Comment by Kazark** [comment]
@yyoncho Here's what I see when I do that (and towards the end I start to get the flood of cancelled messages). Is that what you need?

```
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
======================================================================
1 -> (lsp--on-idle #<buffer <redacted>.scala>)
1 <- lsp--on-idle: nil
```

**Comment by yyoncho** [comment]
Yes, but I want you to share some observation (you could turn on line nubers in the target file).

1. How many entries do you have per movement?
2. Is <redacted> the same buffer?

**Comment by yyoncho** [comment]
To elaborate a bit more, here it is how it works on our side:

1. You do an action(e. g. move your cursor).
2. We track that and schedule a refresh after 0.2 seconds.
3. If you move again we reschedule.
4. If timer has been hit we refresh gui stuff.

**Comment by Kazark** [comment]
I've only got one buffer open ATM, and all the messages are for that buffer. Even if I just position my cursor over one item and wait without moving around, it will be cancelled. I am getting one trace of `lsp--on-idle` per movement.﻿

I thought perhaps the LSP response timeout was being hit, so I've upped it from 10 to 30, but it seems like the timeout happens at 20 seconds.

![Lsp Response Timeout](https://user-images.githubusercontent.com/3661051/72554948-ae95dd00-3869-11ea-8e49-7cea79a72e6f.png)

**Comment by Kazark** [comment]
I did think, though, that the timeout happened a bit faster before I upped that. Let me reset it to 10 since it didn't fix anything and 30 is kind of long, and re-time it.

**Comment by yyoncho** [comment]
The timeout does not affect the async lsp-mode calls. 

Based on your last comment I think that the issue is in the language server not being able to the response before you move the cursor(for some reason). The only fix that we could do on our side is to make the error messages less intrusive. Unfortunately, we have a bug in server logging (we do not log the errors properly) so can you post a screenshot of the echo area (or the place you get the error). Then I think you should follow up with the server-side devs or maybe @kurnevsky might provide some insight since he is more familiar with the server itself.

**Comment by Kazark** [comment]
I'm not sure if this helps, but this is all that shows up in the area below the status bar.

![echo area](https://user-images.githubusercontent.com/3661051/72555857-6d9ec800-386b-11ea-8140-0ba8c47581a4.png)

I think that the fundamental issue here really may be on the Metals side, as you imply. I'll follow up more with them and I appreciate the help.

**Comment by Kazark** [comment]
Yeah, I wonder if there is some way to have a threshhold of, "Hm, we've sent Metals 15 requests, and it hasn't answered anything, better let the user know that this is looking bad on the Metals side," or something like that. 🤷‍♂

**Comment by yyoncho** [comment]
> I'm not sure if this helps, but this is all that shows up in the area below the status bar.

Thank you, this is what I was looking for. Still, it is not clear to me what would be better: burry the error or leave it as it is.

If you want to patch it on your side you could put the following in your spacemacs user config:

``` elisp
(with-eval-after-load 'lsp-mode
   (defun lsp--create-default-error-handler (method)
  "Default error handler.
METHOD is the executed method."
  (lambda (error)
    (lsp--log "%s" (or (gethash "message" error)
                        (format "%s Request has failed" method))))))
```

> Yeah, I wonder if there is some way to have a threshhold of, "Hm, we've sent Metalsthe language server 15 requests, and it hasn't answered anything, better let the user know that this is looking bad on the Metalslanguage server side," or something like that. 

This is a good idea but given the fact that this will happen rarely, it seems like it won't justify the effort . And, yeah, we have tons of work to do right now and we lack manpower.

**Comment by Kazark** [comment]
> we have tons of work to do right now and we lack manpower.

Understood 💯 %.

Ultimately, it's not so much the cancelled messages that are killing me, it's that I don't get the types of things, and it's hard for me to develop without the help of those types (new to Scala here, but not new to statically typed FP, so with types I can move forward rapidly).

However, this doesn't seem to be your problem, so I'll close. Thanks for the help; you've certainly got me closer. We'll see if anybody on the Metals side wants to be this helpful. 🙂
