### ISSUE TITLE
(lsp-empty-response-error . "initialize") on project that is not VC backed

### ISSUE THREAD

**Issue by anmonteiro** [emacs-lsp/lsp-mode#152]
Here's the relevant piece of the stack trace

```
Debugger entered--Lisp error: (lsp-empty-response-error . "initialize")
  signal(lsp-empty-response-error "initialize")
  lsp--start(#s(lsp--client :language-id "ocaml" :send-sync lsp--stdio-send-sync :send-async lsp--stdio-send-async :type nil :new-connection #f(compiled-function (filter sentinel) #<bytecode 0x46063a81>) :get-root lsp-ocaml--get-root :ignore-regexps nil :notification-handlers #<hash-table equal 0/65 0x46063a8d> :request-handlers #<hash-table equal 0/65 0x46063b31> :response-handlers #<hash-table eq 0/65 0x46063b51>))
  lsp-ocaml-enable()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook reason-mode-hook)
```

**Comment by vibhavp** [comment]
Could you post the contents of the *stderr* buffer for the LSP process?

**Comment by anmonteiro** [comment]
Here's the stderr buffer contents from the LSP process:

```
/usr/local/lib/node_modules/ocaml-language-server/bin/server/processes/merlin.js:29
                throw error;
                ^

Error: spawn /bin/sh ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Process lsp-ocaml stderr finished

```

Leads me to believe the bug may be in `ocaml-language-server` rather than emacs-lsp
