### ISSUE TITLE
Unable to make lsp--send-request-async return data in callback

### ISSUE THREAD

**Issue by bizzyman** [emacs-lsp/lsp-mode#263]
_From @bizzyman on January 27, 2018 11:40_

With the following function:
```
(defun simple-lsp-hover-req-async ()
  (lsp--send-request-async (lsp--make-request
                           "textDocument/hover"
                           `(:textDocument (:uri "file:///usr/lib/erlang/lib/jinterface-1.8/java_src/com/ericsson/otp/erlang/AbstractConnection.java")
                                           :position
                                           (:line
                                            147
                                            :character 30)))
                           (lambda (x) (message "HELLO"))
                          ))
```
I am unable to get the lambda callback to fire and show "HELLO" into the echo are or Messages buffer. 
I have tried same function in a python-lsp project and the callback does fire and I am able to see "HELLO" message. The sync version of this function works as expected.

When lsp-print-io is set to t, I see that the server is generating this:
`Output from language server: {"jsonrpc":"2.0","id":"5","result":{"contents":[{"language":"java","value":"void java.io.PrintStream.println(char[] x)"}]}}`
However i get nothing back in the callback, and when lsp-print-io is set to nil I get nothing back.

_Copied from original issue: emacs-lsp/lsp-java#15_

**Comment by bizzyman** [comment]
_From @vibhavp on January 29, 2018 13:43_

Is `inhibit-message` or `lsp-inhibit-message` set to `t`, by any chance? Also, you should probably shift this issue to the `lsp-mode` tracker.

**Comment by bizzyman** [comment]
inhibit-message and lsp-inhibit-message are set to nil

**Comment by vibhavp** [comment]
Have you tried this out with any other language server?

**Comment by bizzyman** [comment]
Yep, I tried with python and it works as expected. I just retried java now with both latest lsp-mode, and the jdt language server and now I get an internal server error when I try to run the async function

This is the stack trace:

Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
	at jdk.internal.jimage.BasicImageReader.slice(BasicImageReader.java:211)
	at jdk.internal.jimage.BasicImageReader.intBuffer(BasicImageReader.java:218)
	at jdk.internal.jimage.BasicImageReader.<init>(BasicImageReader.java:152)
	at jdk.internal.jimage.ImageReader$SharedImageReader.<init>(ImageReader.java:224)
	at jdk.internal.jimage.ImageReader$SharedImageReader.open(ImageReader.java:238)
	at jdk.internal.jimage.ImageReader.open(ImageReader.java:67)
	at jdk.internal.jimage.ImageReader.open(ImageReader.java:71)
	at jdk.internal.jrtfs.SystemImage.open(SystemImage.java:59)
	at jdk.internal.jrtfs.JrtFileSystem.<init>(JrtFileSystem.java:90)
	at jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:108)
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:336)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.initialize(JRTUtil.java:203)
	at org.eclipse.jdt.internal.compiler.util.JrtFileSystem.<init>(JRTUtil.java:184)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.getJrtSystem(JRTUtil.java:111)
	at org.eclipse.jdt.internal.compiler.util.JRTUtil.walkModuleImage(JRTUtil.java:146)
	at org.eclipse.jdt.internal.core.JavaProject.loadModulesInJimage(JavaProject.java:898)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:698)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1007)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:952)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:929)
	at org.eclipse.jdt.internal.core.JavaProject.buildStructure(JavaProject.java:478)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:265)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:593)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:323)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:309)
	at org.eclipse.jdt.internal.core.JavaProject.getModuleDescription(JavaProject.java:3674)
	at org.eclipse.jdt.internal.core.BasicCompilationUnit.initAttributes(BasicCompilationUnit.java:83)
	at org.eclipse.jdt.internal.core.BasicCompilationUnit.<init>(BasicCompilationUnit.java:64)
	at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1134)
	at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:822)
	at org.eclipse.jdt.ls.core.internal.SharedASTProvider$1.run(SharedASTProvider.java:152)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jdt.ls.core.internal.SharedASTProvider.createAST(SharedASTProvider.java:143)
	at org.eclipse.jdt.ls.core.internal.SharedASTProvider.lambda$0(SharedASTProvider.java:73)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.eclipse.jdt.ls.core.internal.SharedASTProvider.getAST(SharedASTProvider.java:71)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentHighlightHandler.computeOccurrences(DocumentHighlightHandler.java:41)
	at org.eclipse.jdt.ls.core.internal.handlers.DocumentHighlightHandler.documentHighlight(DocumentHighlightHandler.java:86)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$10(JDTLanguageServer.java:491)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by yyoncho** [comment]
The JDT was returning String as ID - fixed with https://github.com/emacs-lsp/lsp-mode/pull/313 .
