### ISSUE TITLE
Solargraph server crashes on startup

### ISSUE THREAD

**Issue by thegeorgeous** [emacs-lsp/lsp-mode#3003]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command
```bash
emacs -q -l lsp-start-plain.el
```
where `lsp-start-plain.el` can be downloaded [here](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

### Bug description

Solargraph seems to be crashing on startup

```
Solargraph is listening on stdio PID=96923
#<Thread:0x00000001458f9120@/Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/backport-1.2.0/lib/backport/client.rb:104 run> terminated with exception (report_on_exception is true):
/Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/ripper/sexp.rb:80:in `===': stack level too deep (SystemStackError)
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/ripper/sexp.rb:80:in `block (2 levels) in on_heredoc_dedent'
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/ripper/sexp.rb:75:in `map!'
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/ripper/sexp.rb:75:in `block in on_heredoc_dedent'
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/ripper/sexp.rb:81:in `block (2 levels) in on_heredoc_dedent'
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/ripper/sexp.rb:75:in `map!'
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/ripper/sexp.rb:75:in `block in on_heredoc_dedent'
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/ripper/sexp.rb:81:in `block (2 levels) in on_heredoc_dedent'
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/ripper/sexp.rb:75:in `map!'
	 ... 370 levels...
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/observer.rb:196:in `each'
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/2.6.0/observer.rb:196:in `notify_observers'
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/backport-1.2.0/lib/backport/client.rb:124:in `read_input'
	from /Users/thegeorgeous/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/backport-1.2.0/lib/backport/client.rb:105:in `block in run_input_thread'
```

Doesn't seems to be a solargraph issue because `solargraph stdio` seems to be running fine outside emacs

### Steps to reproduce

Start the `solargraph stdio` server in a Ruby project

### Expected behavior

Solargraph should start without any errors

### Which Language Server did you use?

Language: Ruby
lsp-server: solargraph

### OS

MacOS

### Error callstack

```emacs-lisp
[Trace - 05:55:02 PM] Sending request 'initialize - (1)'.
Params: {
  "processId": null,
  "rootPath": "/Users/thegeorgeous/Workspace/application",
  "clientInfo": {
    "name": "emacs",
    "version": "GNU Emacs 28.0.50 (build 1, aarch64-apple-darwin20.5.0, NS appkit-2022.50 Version 11.4 (Build 20F71))\n of 2021-07-15"
  },
  "rootUri": "file:///Users/thegeorgeous/Workspace/application",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true,
      "fileOperations": {
        "didCreate": false,
        "willCreate": false,
        "didRename": false,
        "willRename": false,
        "didDelete": false,
        "willDelete": false
      }
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true,
        "prepareSupport": true
      },
      "codeAction": {
        "dynamicRegistration": true,
        "isPreferredSupport": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        },
        "resolveSupport": {
          "properties": [
            "edit",
            "command"
          ]
        },
        "dataSupport": true
      },
      "completion": {
        "completionItem": {
          "snippetSupport": true,
          "documentationFormat": [
            "markdown",
            "plaintext"
          ],
          "resolveAdditionalTextEditsSupport": true,
          "insertReplaceSupport": true,
          "resolveSupport": {
            "properties": [
              "documentation",
              "details",
              "additionalTextEdits",
              "command"
            ]
          },
          "insertTextModeSupport": {
            "valueSet": [
              1,
              2
            ]
          }
        },
        "contextSupport": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "documentLink": {
        "dynamicRegistration": true,
        "tooltipSupport": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "foldingRange": null,
      "callHierarchy": {
        "dynamicRegistration": false
      },
      "publishDiagnostics": {
        "relatedInformation": true,
        "tagSupport": {
          "valueSet": [
            1,
            2
          ]
        },
        "versionSupport": true
      },
      "moniker": null,
      "linkedEditingRange": null
    },
    "window": {
      "workDoneProgress": true,
      "showMessage": null,
      "showDocument": null
    }
  },
  "initializationOptions": null,
  "workDoneToken": "1",
  "workspaceFolders": [
    {
      "uri": "file:///Users/thegeorgeous/Workspace/application",
      "name": "application"
    }
  ]
}
```

**Comment by yyoncho** [comment]
can you ask in solargraph repo for pointers on what might be causing this issue? It seems like that initialize request is breaking the server.

**Comment by thegeorgeous** [comment]
Closing this. The issue was with a specific workspace. It had a file with a Squiggly Heredoc string that cannot be parsed by Ripper's sexp method.
