### ISSUE TITLE
PYLSP: TypeError: unhashable type: 'dict' #202 

### ISSUE THREAD

**Issue by swarnendubiswas** [emacs-lsp/lsp-mode#3486]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [X] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

I am using pylsp with Emacs + LSP. I get the following error with a Python source file.

```
2022-04-23 07:27:37,774 IST - ERROR - pylsp_jsonrpc.endpoint - Failed to handle notification workspace/didChangeConfiguration: {'settings': {'pylsp': {'plugins': {'rope_rename': {'enabled': False}, 'autopep8': {'enabled': False}, 'yapf': {'enabled': True}, 'rope_completion': {'enabled': False}, 'pyflakes': {'enabled': False}, 'pydocstyle': {'matchDir': '[^\\.].*', 'match': '(?!test_).*\\.py', 'ignore': ['D100', 'D101', 'D103', 'D213'], 'convention': 'pep257', 'enabled': False}, 'pycodestyle': {'maxLineLength': 100, 'hangClosing': False, 'enabled': False}, 'pylint': {'enabled': True, 'args': ['-j 2', '--rcfile=/home/swarnendu/.config/pylintrc']}, 'flake8': {'enabled': True}, 'preload': {'modules': ['numpy', {',': 'csv'}, {',': 'pandas'}, {',': 'statistics'}, {',': 'json'}], 'enabled': True}, 'mccabe': {'threshold': 15, 'enabled': False}, 'jedi_symbols': {'all_scopes': True, 'enabled': True}, 'jedi_signature_help': {'enabled': True}, 'jedi_references': {'enabled': True}, 'jedi_hover': {'enabled': True}, 'jedi_definition': {'follow_builtin_imports': True, 'follow_imports': True, 'enabled': True}, 'jedi_completion': {'include_params': True, 'enabled': True, 'include_class_objects': True, 'fuzzy': False}, 'jedi_rename': {'enabled': True}}, 'configurationSources': []}}}
Traceback (most recent call last):
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp_jsonrpc/endpoint.py", line 145, in _handle_notification
    handler_result = handler(params)
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp_jsonrpc/dispatchers.py", line 25, in handler
    return method(**(params or {}))
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp/python_lsp.py", line 388, in m_workspace__did_change_configuration
    self.config.update((settings or {}).get('pylsp', {}))
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp/config/config.py", line 168, in update
    self._update_disabled_plugins()
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp/config/config.py", line 172, in _update_disabled_plugins
    self._disabled_plugins = [
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp/config/config.py", line 174, in <listcomp>
    if not self.settings().get('plugins', {}).get(name, {}).get('enabled', True)
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp/config/config.py", line 132, in settings
    settings = _utils.merge_dicts(settings, self._settings)
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp/_utils.py", line 143, in merge_dicts
    return dict(_merge_dicts_(dict_a, dict_b))
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp/_utils.py", line 132, in _merge_dicts_
    yield (key, dict(_merge_dicts_(a[key], b[key])))
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp/_utils.py", line 132, in _merge_dicts_
    yield (key, dict(_merge_dicts_(a[key], b[key])))
  File "/home/swarnendu/.local/lib/python3.8/site-packages/pylsp/_utils.py", line 134, in _merge_dicts_
    yield (key, list(set(a[key] + b[key])))
TypeError: unhashable type: 'dict'
2022-04-23 07:27:37,776 IST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 2
2022-04-23 07:27:37,917 IST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 4
2022-04-23 07:27:37,933 IST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 3
2022-04-23 07:27:37,934 IST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 6
2022-04-23 07:27:37,934 IST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 5
2022-04-23 07:27:38,137 IST - WARNING - pylsp.config.config - Failed to load hook pylsp_completions: unhashable type: 'dict'
2022-04-23 07:27:38,435 IST - WARNING - pylsp.config.config - Failed to load hook pylsp_lint: unhashable type: 'dict'
2022-04-23 07:28:45,625 IST - WARNING - pylsp.config.config - Failed to load hook pylsp_lint: unhashable type: 'dict'
```

The OS is Ubuntu 20.04, Python version is 3.8.10, and pylsp is 1.4.1. I can reproduce the error on multiple machines. I reported this to PYLSP team and they suggest there is a possible error with the PYLSP client. 

https://github.com/python-lsp/python-lsp-server/issues/202

### Steps to reproduce

Open a Python file with `pylsp` and try completions.

### Expected behavior

I expect auto-complete to work but it is not working.

### Which Language Server did you use?

pylsp

### OS

Linux

### Error callstack

```emacs-lisp
[Trace - 09:46:22 PM] Sending request 'initialize - (1)'.
Params: {
  "processId": null,
  "rootPath": "/home/swarnendu/bitbucket/iitkanpur",
  "clientInfo": {
    "name": "emacs",
    "version": "GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.32, cairo version 1.16.0)\n of 2022-04-13"
  },
  "rootUri": "file:///home/swarnendu/bitbucket/iitkanpur",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true,
      "codeLens": {
        "refreshSupport": true
      },
      "fileOperations": {
        "didCreate": false,
        "willCreate": false,
        "didRename": false,
        "willRename": false,
        "didDelete": false,
        "willDelete": false
      }
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true,
        "prepareSupport": true
      },
      "codeAction": {
        "dynamicRegistration": true,
        "isPreferredSupport": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        },
        "resolveSupport": {
          "properties": [
            "edit",
            "command"
          ]
        },
        "dataSupport": true
      },
      "completion": {
        "completionItem": {
          "snippetSupport": true,
          "documentationFormat": [
            "markdown",
            "plaintext"
          ],
          "resolveAdditionalTextEditsSupport": true,
          "insertReplaceSupport": true,
          "deprecatedSupport": true,
          "resolveSupport": {
            "properties": [
              "documentation",
              "details",
              "additionalTextEdits",
              "command"
            ]
          },
          "insertTextModeSupport": {
            "valueSet": [
              1,
              2
            ]
          }
        },
        "contextSupport": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "documentLink": {
        "dynamicRegistration": true,
        "tooltipSupport": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "foldingRange": null,
      "callHierarchy": {
        "dynamicRegistration": false
      },
      "publishDiagnostics": {
        "relatedInformation": true,
        "tagSupport": {
          "valueSet": [
            1,
            2
          ]
        },
        "versionSupport": true
      },
      "linkedEditingRange": {
        "dynamicRegistration": true
      }
    },
    "window": {
      "workDoneProgress": true,
      "showMessage": null,
      "showDocument": {
        "support": true
      }
    }
  },
  "initializationOptions": null,
  "workDoneToken": "1"
}


[Trace - 09:46:24 PM] Received response 'initialize - (1)' in 281ms.
Result: {
  "capabilities": {
    "codeActionProvider": true,
    "codeLensProvider": {
      "resolveProvider": null
    },
    "completionProvider": {
      "resolveProvider": true,
      "triggerCharacters": [
        "."
      ]
    },
    "documentFormattingProvider": true,
    "documentHighlightProvider": true,
    "documentRangeFormattingProvider": true,
    "documentSymbolProvider": true,
    "definitionProvider": true,
    "executeCommandProvider": {
      "commands": []
    },
    "hoverProvider": true,
    "referencesProvider": true,
    "renameProvider": true,
    "foldingRangeProvider": true,
    "signatureHelpProvider": {
      "triggerCharacters": [
        "(",
        ",",
        "="
      ]
    },
    "textDocumentSync": {
      "change": 2,
      "save": {
        "includeText": true
      },
      "openClose": true
    },
    "workspace": {
      "workspaceFolders": {
        "supported": true,
        "changeNotifications": true
      }
    },
    "experimental": {}
  },
  "serverInfo": {
    "name": "pylsp",
    "version": "1.4.1"
  }
}


[Trace - 09:46:24 PM] Sending notification 'initialized'.
Params: {}


[Trace - 09:46:24 PM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
  "settings": {
    "pylsp": {
      "plugins": {
        "rope_rename": {
          "enabled": false
        },
        "autopep8": {
          "enabled": false
        },
        "yapf": {
          "enabled": true
        },
        "rope_completion": {
          "enabled": false
        },
        "pyflakes": {
          "enabled": false
        },
        "pydocstyle": {
          "matchDir": "[^\\.].*",
          "match": "(?!test_).*\\.py",
          "ignore": [
            "D100",
            "D101",
            "D103",
            "D213"
          ],
          "convention": "pep257",
          "enabled": false
        },
        "pycodestyle": {
          "maxLineLength": 100,
          "hangClosing": false,
          "enabled": false
        },
        "pylint": {
          "enabled": true,
          "args": [
            "-j 2",
            "--rcfile=/home/swarnendu/.config/pylintrc"
          ]
        },
        "flake8": {
          "enabled": true
        },
        "preload": {
          "modules": [
            "numpy",
            [
              ",",
              "csv"
            ],
            [
              ",",
              "pandas"
            ],
            [
              ",",
              "statistics"
            ],
            [
              ",",
              "json"
            ]
          ],
          "enabled": true
        },
        "mccabe": {
          "threshold": 15,
          "enabled": false
        },
        "jedi_symbols": {
          "all_scopes": true,
          "enabled": true
        },
        "jedi_signature_help": {
          "enabled": true
        },
        "jedi_references": {
          "enabled": true
        },
        "jedi_hover": {
          "enabled": true
        },
        "jedi_definition": {
          "follow_builtin_imports": true,
          "follow_imports": true,
          "enabled": true
        },
        "jedi_completion": {
          "include_params": true,
          "enabled": true,
          "include_class_objects": true,
          "fuzzy": false
        },
        "jedi_rename": {
          "enabled": true
        }
      },
      "configurationSources": []
    }
  }
}


[Trace - 09:46:24 PM] Sending notification 'textDocument/didOpen'.
Params: {
  "textDocument": {
    "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py",
    "languageId": "python",
    "version": 0,
    "text": "import os\nimport csv\nimport sys\nimport statistics\n\nPRECISION = 2\n\nLABS_INFO = {\n    \"lab1\": 140,\n    \"lab2\": 145,\n    \"lab3\": 400,\n    \"lab4\": 163,\n    \"lab5\": 120,\n    \"lab6\": 80,\n    \"lab7\": 300,\n    \"lab8\": 210,\n    \"lab9\": 55,\n    \"lab10\": 120,\n    \"lab11\": 195\n}\nLAB_WEIGHT = 7\nMK_LABS_INFO = {\"makeup-lab1\": 190, \"makeup-lab2\": 120}\n\nQUIZZES_INFO = {\"quiz1\": 150, \"quiz2\": 150, \"quiz3\": 150}\nQUIZ_WEIGHT = 10\nMK_QUIZZES_INFO = {\"makeup-quiz1\"}\n\nLAB_MARKS_CSV_NAME = \"labMarksEvent_Absolute.csv\"\nLAB_NAME_IDX = 0\nLAB_EMAIL_IDX = LAB_NAME_IDX + 1\nLAB_ROLLNO_IDX = LAB_EMAIL_IDX + 1\nLAB_SECTION_IDX = LAB_ROLLNO_IDX + 1\nLAB_MARKS_IDX = LAB_SECTION_IDX + 1\n\nQUIZ_MARKS_CSV_NAME = \"section-c-final.csv\"\nQUIZ_ROLLNO_IDX = 0\nQUIZ_NAME_IDX = QUIZ_ROLLNO_IDX + 1\nQUIZ_EMAIL_IDX = QUIZ_NAME_IDX + 1\nQUIZ_SECTION_IDX = QUIZ_EMAIL_IDX + 1\nQUIZ_MOOKIT_IDX = QUIZ_SECTION_IDX + 1\nQUIZ_PRUTOR_IDX = QUIZ_MOOKIT_IDX + 1\nQUIZ_TOTAL_STR = \"Total\"\n\n\ndef main():\n    # Finalize cheating data\n    students = {}\n    for root, _, filenames in os.walk(\"./cheating-reports\"):\n        for filename in filenames:\n            csv_path: str = os.path.join(root, filename)  # Path to one log file\n            ROLLNO1_IDX = -1\n            ROLLNO2_IDX = -1\n\n            rollset = set()  # A roll number may appear multiple times\n            with open(csv_path, encoding=\"utf-8\") as infile:\n                csv_reader = csv.reader(infile, delimiter=',')\n                line_count = 0\n                for row in csv_reader:\n                    line_count += 1\n                    if line_count > 1:\n                        rollno1: int = int(row[ROLLNO1_IDX])\n                        if rollno1 > 0:\n                            rollset.add(rollno1)\n                        rollno2: int = int(row[ROLLNO2_IDX])\n                        if rollno2 > 0:\n                            rollset.add(rollno2)\n                    else:\n                        ROLLNO1_IDX = row.index(\"Rollno1\")\n                        ROLLNO2_IDX = row.index(\"Rollno2\")\n\n            for roll in rollset:\n                students[roll] = students.get(roll, 0) + 1\n\n            rollset.clear()\n\n    # Compute marks\n    data = {}\n\n    # Read Lab data\n    for lab, maxm in LABS_INFO.items():\n        csv_path: str = lab + os.sep + LAB_MARKS_CSV_NAME\n        with open(csv_path, encoding=\"utf-8\") as infile:\n            csv_reader = csv.reader(infile, delimiter=',')\n            line_count = 0\n            for row in csv_reader:\n                line_count += 1\n                if line_count > 1:\n                    rollno: int = int(row[LAB_ROLLNO_IDX])\n                    marks: float = round(float(row[LAB_MARKS_IDX]) / maxm * LAB_WEIGHT, PRECISION)\n                    if rollno in data:\n                        tmp = data[rollno]\n                        tmp[\"labs\"].append(marks)\n                        assert len(tmp[\"labs\"]) <= len(LABS_INFO)\n                    else:  # Student data does not exist\n                        tmp = {\n                            \"name\": row[LAB_NAME_IDX],\n                            \"email\": row[LAB_EMAIL_IDX],\n                            \"rollno\": rollno\n                        }\n                        tmp[\"labs\"] = [marks]\n                        assert row[LAB_SECTION_IDX] != \"DAP\"\n                        # Leave out Section D\n                        if row[LAB_SECTION_IDX].startswith(\"D\"):\n                            continue\n                        data[rollno] = tmp\n\n    # Read Quiz data\n    for quiz, maxm in QUIZZES_INFO.items():\n        csv_path: str = quiz + os.sep + QUIZ_MARKS_CSV_NAME\n        with open(csv_path, encoding=\"utf-8\") as infile:\n            csv_reader = csv.reader(infile, delimiter=',')\n            line_count = 0\n            total_idx = -1\n            for row in csv_reader:\n                line_count += 1\n                if line_count == 1:\n                    total_idx = row.index(QUIZ_TOTAL_STR)\n                else:\n                    rollno: int = int(row[QUIZ_ROLLNO_IDX])\n                    if rollno in data:\n                        tmp = data[rollno]\n                        marks: float = round(float(row[total_idx]) / maxm * QUIZ_WEIGHT, PRECISION)\n                        if \"quizzes\" in tmp:\n                            tmp[\"quizzes\"].append(marks)\n                            assert len(tmp[\"quizzes\"]) <= len(QUIZZES_INFO)\n                        else:\n                            tmp[\"quizzes\"] = [marks]\n\n    # Read makeup lab data\n    for lab, maxm in MK_LABS_INFO.items():\n        csv_path: str = lab + os.sep + LAB_MARKS_CSV_NAME\n        with open(csv_path, encoding=\"utf-8\") as infile:\n            csv_reader = csv.reader(infile, delimiter=\",\")\n            line_count = 0\n            for row in csv_reader:\n                line_count += 1\n                if line_count > 1:\n                    rollno: int = int(row[LAB_ROLLNO_IDX])\n                    if rollno in data:\n                        marks: float = (float(row[LAB_MARKS_IDX]) / maxm) * LAB_WEIGHT\n                        tmp = data[rollno]\n                        # Count nonzeros\n                        nonzeros = sum(1 for x in tmp[\"labs\"] if x > 0)\n                        if nonzeros >= len(LABS_INFO):\n                            print(f\"Exceeding lab count: {row}\")\n                            sys.exit()\n                        assert nonzeros < len(LABS_INFO)\n                        if len(tmp[\"labs\"]) == len(LABS_INFO):\n                            # Remove a zero element\n                            tmp[\"labs\"].remove(0)\n                        tmp[\"labs\"].append(marks)\n\n    for rollno, stud in data.items():\n        stud[\"labs\"].sort(reverse=True)\n        # Leave out the poorest\n        try:\n            lab_comp: float = sum(stud[\"labs\"][:-1])\n            quiz_comp: float = sum(stud[\"quizzes\"])\n            stud[\"total\"] = round(lab_comp + quiz_comp, PRECISION)\n        except KeyError:\n            print(stud)\n            sys.exit()\n\n    sorted_data = []\n    for _, v in sorted(data.items(), key=lambda item: item[1][\"total\"], reverse=True):\n        sorted_data.append(v)\n\n    # Penalize repeat offenders, 10% for 4-5 labs, and 15% for 6+ labs.\n    num_offenders: int = 0\n    for elem in sorted_data:\n        rollno: int = elem[\"rollno\"]\n        count = students.get(rollno, 0)\n        if count >= 6:\n            elem[\"total\"] = elem[\"total\"] * 0.85\n            elem[\"repeat-offender\"] = \">=6\"\n            num_offenders += 1\n        elif 4 <= count <= 5:\n            elem[\"total\"] = elem[\"total\"] * 0.90\n            elem[\"repeat-offender\"] = \"4-5\"\n            num_offenders += 1\n        else:\n            elem[\"repeat-offender\"] = \"<=3\"\n\n    print(f\"Number of >=4 repeat offenders: {num_offenders}\")\n\n    # with open(\"cumulative.json\", \"w\", encoding=\"utf-8\") as outfile:\n    #     json.dump(sorted_data, outfile)\n\n    keys = sorted_data[0].keys()\n    with open(\"cumulative.csv\", 'w', newline='', encoding=\"utf-8\") as outfile:\n        dict_writer = csv.DictWriter(outfile, keys)\n        dict_writer.writeheader()\n        dict_writer.writerows(sorted_data)\n\n    # Compute class statistics\n    stud_list = list(data.values())\n    total = [d['total'] for d in stud_list]\n    print(f\"Class mean: {round(statistics.mean(total), PRECISION)} \"\n          f\"median: {round(statistics.median(total), PRECISION)} \"\n          f\"stdev: {round(statistics.stdev(total), PRECISION)}\")\n\n    # with open(\"counselling-services.json\", \"w\", encoding=\"utf-8\") as outfile:\n    #     json.dump(sorted_data[-100:], outfile)\n\n\nif __name__ == \"__main__\":\n    main()\n"
  }
}


[Trace - 09:46:24 PM] Sending request 'textDocument/codeLens - (2)'.
Params: {
  "textDocument": {
    "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py"
  }
}


[Trace - 09:46:24 PM] Sending notification '$/cancelRequest'.
Params: {
  "id": 2
}


[Trace - 09:46:24 PM] Sending request 'textDocument/codeLens - (3)'.
Params: {
  "textDocument": {
    "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py"
  }
}


[Trace - 09:46:24 PM] Sending request 'textDocument/codeAction - (4)'.
Params: {
  "textDocument": {
    "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py"
  },
  "range": {
    "start": {
      "line": 207,
      "character": 0
    },
    "end": {
      "line": 207,
      "character": 0
    }
  },
  "context": {
    "diagnostics": []
  }
}


[Trace - 09:46:24 PM] Sending request 'textDocument/documentHighlight - (5)'.
Params: {
  "textDocument": {
    "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py"
  },
  "position": {
    "line": 207,
    "character": 0
  }
}


[Trace - 09:46:24 PM] Sending notification '$/cancelRequest'.
Params: {
  "id": 4
}


[Trace - 09:46:24 PM] Sending request 'textDocument/codeAction - (6)'.
Params: {
  "textDocument": {
    "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py"
  },
  "range": {
    "start": {
      "line": 207,
      "character": 0
    },
    "end": {
      "line": 207,
      "character": 0
    }
  },
  "context": {
    "diagnostics": []
  }
}


[Trace - 09:46:24 PM] Sending notification '$/cancelRequest'.
Params: {
  "id": 5
}


[Trace - 09:46:24 PM] Sending request 'textDocument/documentHighlight - (7)'.
Params: {
  "textDocument": {
    "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py"
  },
  "position": {
    "line": 207,
    "character": 0
  }
}


[Trace - 09:46:24 PM] Sending notification '$/cancelRequest'.
Params: {
  "id": 3
}


[Trace - 09:46:24 PM] Sending request 'textDocument/codeLens - (8)'.
Params: {
  "textDocument": {
    "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py"
  }
}


[Trace - 09:46:24 PM] Received response 'nil - (2)' in 0ms.
Result: []


[Trace - 09:46:24 PM] Received response 'nil - (3)' in 0ms.
Result: []


[Trace - 09:46:24 PM] Received response 'nil - (4)' in 0ms.
Result: []


[Trace - 09:46:24 PM] Received response 'nil - (5)' in 0ms.
Result: null


[Trace - 09:46:24 PM] Received response 'textDocument/codeAction - (6)' in 100ms.
Result: []


[Trace - 09:46:24 PM] Received response 'textDocument/documentHighlight - (7)' in 99ms.
Result: null


[Trace - 09:46:24 PM] Received response 'textDocument/codeLens - (8)' in 34ms.
Result: []


[Trace - 09:46:24 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py",
  "diagnostics": []
}


[Trace - 09:46:24 PM] Sending request 'textDocument/codeAction - (9)'.
Params: {
  "textDocument": {
    "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py"
  },
  "range": {
    "start": {
      "line": 207,
      "character": 0
    },
    "end": {
      "line": 207,
      "character": 0
    }
  },
  "context": {
    "diagnostics": []
  }
}


[Trace - 09:46:24 PM] Sending request 'textDocument/documentHighlight - (10)'.
Params: {
  "textDocument": {
    "uri": "file:///home/swarnendu/bitbucket/iitkanpur/courses/autumn2021-esc101/final-marks.py"
  },
  "position": {
    "line": 207,
    "character": 0
  }
}


[Trace - 09:46:24 PM] Received response 'textDocument/codeAction - (9)' in 77ms.
Result: []


[Trace - 09:46:24 PM] Received response 'textDocument/documentHighlight - (10)' in 77ms.
Result: null
```

**Comment by sylph1o** [comment]
Hi! I seem to be facing the same issue. @swarnendubiswas have you solved this? Do you have any more clue?

**Comment by sylph1o** [comment]
I have found the issue and I believe @swarnendubiswas had the same. Of course it was my fault, because my configuration was wrong, but it was not immediately obvious.

Here is only the relevant part of my erroneous configuration:
```lisp
(setopt lsp-pylsp-configuration-sources ["ruff", "pylsp-mypy"])
(lsp-register-custom-settings
       ("pylsp.plugins.ruff.select" ["E", "F", "B", "D", "W", "I", "ANN"] t)
       ("pylsp.plugins.ruff.extendIgnore" ["E203", "W505"] t)
)
```
Fortunately the log of the error raised by `pylsp` on `workspace/didChangeConfiguration` contained the configuration received, and I could see that the configuration above became something like `{'select': ['E', {',': 'F'}, {',': 'B'}, ...]}` instead of the expected `{'select': ['E', 'F', 'B', ...]}`. The error were the commas, so here is the correct configuration:
```lisp
(setopt lsp-pylsp-configuration-sources ["ruff" "pylsp-mypy"])
(lsp-register-custom-settings
       ("pylsp.plugins.ruff.select" ["E" "F" "B" "D" "W" "I" "ANN"] t)
       ("pylsp.plugins.ruff.extendIgnore" ["E203" "W505"] t)
)
```

I believe that @swarnendubiswas had made the same mistake, given this excerpt from the first line of his error log:
```python
'preload': {'modules': ['numpy', {',': 'csv'}, {',': 'pandas'}, {',': 'statistics'}, {',': 'json'}], 'enabled': True}
```

As far as I am concerned this issue is solved, but I would be interested to know where I could have found the documentation for this syntax. I believe I had seen somewhere the syntax with one element (e.g. `(setopt lsp-pylsp-configuration-sources ["flake8"])` ) and the square brackets mislead me into extrapolating to multiple elements with the Python syntax. 
I did search the `lsp-pylsp` documentation, but all I could find was that the value had to be of type `lsp-string-vector` (but not what it looked like). It would be nice to know where to find the relevant documentation, especially since these square brackets are unusual for me in Lisp (admittedly most of Lisp is unusual to me).

**Comment by swarnendubiswas** [comment]
Thanks @sylph1o
