### ISSUE TITLE
Provide Language Server for Apache Camel

### ISSUE THREAD

**Issue by apupier** [emacs-lsp/lsp-mode#3528]
Is your feature related or already mentioned on [the wishlist](https://github.com/emacs-lsp/lsp-mode/discussions/2892)? No

There is a [Language Server for Apache Camel](https://github.com/camel-tooling/camel-language-server). It would be nice having it built-in. [Apache Camel](https://camel.apache.org/) is an Open Source integration framework that empowers you to quickly and easily integrate various systems consuming or producing data. It is one of the top active projects in Apache foundation.

The server is written in Java so I guess a good example on how to integrate it is the [Language Server for xml integration](https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-xml.el).
The Camel LSP jar is available here https://repo1.maven.org/maven2/com/github/camel-tooling/camel-lsp-server/1.5.0/camel-lsp-server-1.5.0.jar

A specificity of Apache Camel is that it is working with several languages: java, xml, yaml. As a first iteration, we can imagine to enable it for a single language.
There are several settings potentially available ([Camel Catalog version](https://github.com/camel-tooling/camel-language-server#specific-version-of-camel-catalog), [Camel runtime provider](https://github.com/camel-tooling/camel-language-server#specific-runtime-provider-of-camel-catalog), [Additional Camel component](https://github.com/camel-tooling/camel-language-server#additional-camel-components) but as a first iteration i think we can ignore all of them. None are mandatory.

Questions: Are there some tests to implement to incorporate the additional language? or the tests are only checking core features of lsp-mode?

**Comment by yyoncho** [comment]
> Questions: Are there some tests to implement to incorporate the additional language? or the tests are only checking core features of lsp-mode?

Usually, once the server is initialized properly it tends to work OOTB so checking the basic features should be good enough.

**Comment by Navyashree0923** [comment]
Hello @yyoncho I have created a file `lsp-camel.el` by referring `lsp-xml.el`. I have placed this file under `"~/.emacs.d/elpa/lsp-mode-8.0.0"`. 

This is the content my `lsp-camel.el` file.

```
;;; lsp-camel.el --- LSP Camel server integration        -*- lexical-binding: t; -*-
 
 
;;; Code:
 
(require 'lsp-mode)
 
(defgroup lsp-camel nil
  "LSP support for Camel, using camel-language-server"
  :group 'lsp-mode
  :tag "Language Server"
  :package-version '(lsp-mode . "8.0.0"))
 
;; Define a variable to store camel language server jar version
(defconst lsp-camel-jar-version "1.5.0")
 
;; Define a variable to store camel language server jar name
(defconst lsp-camel-jar-name (format "camel-lsp-server-%s.jar" lsp-xml-jar-version))
 
;; Directory in which the servers will be installed. Lsp Server Install Dir: /home/npr/.emacs.d/.cache/camells/camel-lsp-server-1.5.0.jar
(defcustom lsp-camel-jar-file (f-join lsp-server-install-dir "camells" lsp-camel-jar-name)
  "Camel Language server jar command."
  :type 'string
  :group 'lsp-camel
  :type 'file
  :package-version '(lsp-mode . "8.0.0"))
 
(defcustom lsp-camel-jar-download-url
  (format "https://repo1.maven.org/maven2/com/github/camel-tooling/camel-lsp-server/%s/%s" lsp-camel-jar-version lsp-camel-jar-name)
  "Automatic download url for lsp-camel."
  :type 'string
  :group 'lsp-camel
  :package-version '(lsp-mode . "8.0.0"))
 
(lsp-dependency
 'camells
 '(:system lsp-camel-jar-file)
 `(:download :url lsp-camel-jar-download-url
             :store-path lsp-camel-jar-file))
 
(defcustom lsp-camel-server-command `("java" "-jar" , lsp-camel-jar-file)
  "Camel server command."
  :type '(repeat string)
  :group 'lsp-camel
  :package-version '(lsp-mode . "8.0.0"))
 
(defun lsp-camel--create-connection ()
  (lsp-stdio-connection
   (lambda () lsp-camel-server-command)
   (lambda () (f-exists? lsp-camel-jar-file))))
 
(lsp-register-client
 (make-lsp-client :new-connection (lsp-camel--create-connection)
                  :activation-fn (lsp-activate-on "nxml")
                  :priority 0
                  :server-id 'camells
                  :multi-root t
                  :initialized-fn (lambda (workspace)
                                    (with-lsp-workspace workspace
                                      (lsp--set-configuration (lsp-configuration-section "camel"))))
                  :download-server-fn (lambda (_client callback error-callback _update?)
                                        (lsp-package-ensure 'camells callback error-callback))))
 
(lsp-consistency-check lsp-camel)
 
(provide 'lsp-camel)
;;; lsp-camel.el ends here
```

Please do you have pointers on how do I list camel lsp server automatically when i run `M-x lsp-install-server RET` ? 
Please is there any sequence of steps that I should  follow in order to achieve this task?

**Comment by yyoncho** [comment]
@apupier Refer to this PR - https://github.com/emacs-lsp/lsp-mode/pull/3444/ - there are a few more places you should touch.

**Comment by Navyashree0923** [comment]
Thank you for the suggestion. I'll go through this PR now

**Comment by Navyashree0923** [comment]
Hello @yyoncho please these are the minimal changes that I made to my `init.el`
```
cat ~/.emacs.d/init.el
;; MELPA package repository
(add-to-list 'package-archives
	     '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(lsp-log-io t)
 '(package-selected-packages
   '(treemacs-all-the-icons lsp-ui lsp-java lsp-ivy jedi helm-lsp flymake flycheck elpy company-ycmd company-jedi anaconda-mode)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )


;;; Code:

(require 'lsp-mode)

'(lsp-register-client
  (make-lsp-client :new-connection (lsp-stdio-connection "/usr/bin/java" "-jar", "/home/npr/camel-lsp-server-1.5.0.jar")
                  :activation-fn (lsp-activate-on "nxml")
                  :add-on? t))


;; Automatically start a language server based on the current programming language opened in the buffer by adding hook
;; (add-hook 'nxml-mode-hook #'lsp)


```
Now I'm using this config file to create a camel LS client. When I run `M-x: lsp` on a `.xml` file it is automatically connecting to a xml language server but not both. Could you please me understand how should I proceed further on this issue?

Thanks in advance

**Comment by yyoncho** [comment]
The language server should run side by side with the xml language server or it should run over specific files?

>  :activation-fn (lsp-activate-on "nxml")

This should be `xml`.

**Comment by Navyashree0923** [comment]
Thanks for simplifying it. My objective is that language server should run side by side with the xml language server

**Comment by yyoncho** [comment]
Ok, after changing the activate-on language what happens after `M-x lsp`? You may check also `*lsp-log*` buffer

**Comment by Navyashree0923** [comment]
Changed it to `xml`. Just like before it is connecting to xml language server now when i ran `lsp` on a `.xml` file and it's major-mode is set to `"nxml-mode"`.

>You may check also *lsp-log* buffer

Please I did see similar statement at the Troubleshooting page but not sure how to leverage it to see the logs. But my  `Lsp Log Io` is ON. 

```
Hide Lsp Log Io: Toggle  on (non-nil) State : SAVED and set.
 If non-nil, log all messages from the language server to a *lsp-log* buffer.
Groups: Language Server (lsp-mode)
```

Please point me how to take this further.

**Comment by yyoncho** [comment]
> Please I did see similar statement at the Troubleshooting page but not sure how to leverage it to see the logs. But my Lsp Log Io is ON.

`C-x b` and look for \*lsp-log\* buffer.

**Comment by yyoncho** [comment]
Also, make sure that the file containing the content you have added is evaluated when testing

**Comment by Navyashree0923** [comment]
Thank you for such a quick response. I see this lines in `*lsp-log*`
```
Found the following clients for /home/npr/emacs_xml_files/b.xml: (server-id xmlls, priority 0)
The following clients were selected based on priority: (server-id xmlls, priority 0)
Creating watchers for following 1 folders:
  /home/npr/emacs_xml_files
May 26, 2022 04:09:35 org.eclipse.lemminx.logs.LogHelper initializeRootLogger()
Message: Log file could not be created, path not provided
May 26, 2022 04:09:35 org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry registerExtension()
Message: Error while initializing extension <org.eclipse.lemminx.extensions.catalog.XMLCatalogPlugin>
java.lang.NullPointerException
	at java.base/java.util.Arrays.stream(Arrays.java:5614)
	at org.eclipse.lemminx.extensions.catalog.XMLCatalogPlugin.validateCatalogPaths(XMLCatalogPlugin.java:70)
	at org.eclipse.lemminx.extensions.catalog.XMLCatalogPlugin.doSave(XMLCatalogPlugin.java:47)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.registerExtension(XMLExtensionsRegistry.java:201)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.lambda$initialize$2(XMLExtensionsRegistry.java:191)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initialize(XMLExtensionsRegistry.java:190)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.initializeIfNeeded(XMLExtensionsRegistry.java:180)
	at org.eclipse.lemminx.services.extensions.XMLExtensionsRegistry.getDiagnosticsParticipants(XMLExtensionsRegistry.java:132)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:83)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:53)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:159)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:168)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:466)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$triggerValidationFor$23(XMLTextDocumentService.java:459)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```


> Also, make sure that the file containing the content you have added is evaluated when testing

I believe my file content has necessary lines to inspect the camel language server. But a small question, if you look at this comment https://github.com/emacs-lsp/lsp-mode/issues/3528#issuecomment-1138187320, I have added a single quote `'` before `(lsp-register-client` to avoid this errors. 

```
Debugger entered--Lisp error: (void-function \,)
  ,"/home/npr/camel-lsp-server-1.5.0.jar"
  (lsp-stdio-connection "/usr/bin/java" "-jar" ,"/home/npr/camel-lsp-server-1.5.0.jar")
  (make-lsp-client :new-connection (lsp-stdio-connection "/usr/bin/java" "-jar" ,"/home/npr/camel-lsp-server-1.5.0.jar") :activation-fn (lsp-activate-on "xml") :add-on\? t)
  (lsp-register-client (make-lsp-client :new-connection (lsp-stdio-connection "/usr/bin/java" "-jar" ,"/home/npr/camel-lsp-server-1.5.0.jar") :activation-fn (lsp-activate-on "xml") :add-on\? t))
  eval-buffer(#<buffer  *load*> nil "/home/npr/.emacs.d/init.el" nil t)  ; Reading at buffer position 1053
  load-with-code-conversion("/home/npr/.emacs.d/init.el" "/home/npr/.emacs.d/init.el" t t)
  load("/home/npr/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x743835>) #f(compiled-function () #<bytecode 0x743761>) t)
  command-line()
  normal-top-level()
```

Please do you believe this could have something to do here :)

**Comment by yyoncho** [comment]
```
;;; lsp-camel.el --- LSP Camel server integration        -*- lexical-binding: t; -*-


;;; Code:

(require 'lsp-mode)

(defgroup lsp-camel nil
  "LSP support for Camel, using camel-language-server"
  :group 'lsp-mode
  :tag "Language Server"
  :package-version '(lsp-mode . "8.0.0"))

;; Define a variable to store camel language server jar version
(defconst lsp-camel-jar-version "1.5.0")

;; Define a variable to store camel language server jar name
(defconst lsp-camel-jar-name (format "camel-lsp-server-%s.jar" lsp-xml-jar-version))

;; Directory in which the servers will be installed. Lsp Server Install Dir: /home/npr/.emacs.d/.cache/camells/camel-lsp-server-1.5.0.jar
(defcustom lsp-camel-jar-file (f-join lsp-server-install-dir "camells" lsp-camel-jar-name)
  "Camel Language server jar command."
  :type 'string
  :group 'lsp-camel
  :type 'file
  :package-version '(lsp-mode . "8.0.0"))

(defcustom lsp-camel-jar-download-url
  (format "https://repo1.maven.org/maven2/com/github/camel-tooling/camel-lsp-server/%s/%s" lsp-camel-jar-version lsp-camel-jar-name)
  "Automatic download url for lsp-camel."
  :type 'string
  :group 'lsp-camel
  :package-version '(lsp-mode . "8.0.0"))

(lsp-dependency
 'camells
 '(:system lsp-camel-jar-file)
 `(:download :url lsp-camel-jar-download-url
             :store-path lsp-camel-jar-file))

(defcustom lsp-camel-server-command `("java" "-jar" , lsp-camel-jar-file)
  "Camel server command."
  :type '(repeat string)
  :group 'lsp-camel
  :package-version '(lsp-mode . "8.0.0"))

(defun lsp-camel--create-connection ()
  (lsp-stdio-connection
   (lambda () lsp-camel-server-command)
   (lambda () (f-exists? lsp-camel-jar-file))))

(lsp-register-client
 (make-lsp-client :new-connection (lsp-camel--create-connection)
                  :activation-fn (lsp-activate-on "xml")
                  :priority 0
                  :server-id 'camells
                  :add-on? t
                  :multi-root t
                  :initialized-fn (lambda (workspace)
                                    (with-lsp-workspace workspace
                                      (lsp--set-configuration (lsp-configuration-section "camel"))))
                  :download-server-fn (lambda (_client callback error-callback _update?)
                                        (lsp-package-ensure 'camells callback error-callback))))

(lsp-consistency-check lsp-camel)

(provide 'lsp-camel)
;;; lsp-camel.el ends here
```


I used this content, evaluated it. Then I did `M-x lsp-download-server` and picked camel. Note that URL that you have now is 404, so you have to fix it first. After that M-x lsp tries to start camel server. It failed because the jar was not correct but I guess it will start correctly if you have the correct jar.

**Comment by yyoncho** [comment]
it is lsp-install-server, not `lsp-download-server`

**Comment by Navyashree0923** [comment]
Sorry, I am not able to list camel in `lsp-install-server` but i can see lot of other language servers. Please does it have anything to do with `lsp-camel.el` file path. Currently this is present here `~/.emacs.d/elpa/lsp-mode-8.0.0/lsp-camel.el`. 

> Note that URL that you have now is 404, so you have to fix it first.
Sure i will update it.

**Comment by yyoncho** [comment]
@apupier have you loaded the file? M-x eval-buffer.

**Comment by apupier** [comment]
Managed to have the Camel LS alongside the XML LS:

- in init.el file:
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(lsp-mode)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
 
(require 'lsp-mode)
(add-hook 'nxml-mode-hook #'lsp)
```
- in a lsp-camel.el file:
 ```
 ;;; lsp-camel.el --- LSP Camel server integration        -*- lexical-binding: t; -*-


;;; Code:

(require 'lsp-mode)

(defgroup lsp-camel nil
  "LSP support for Camel, using camel-language-server"
  :group 'lsp-mode
  :tag "Language Server"
  :package-version '(lsp-mode . "8.0.0"))

;; Define a variable to store camel language server jar version
(defconst lsp-camel-jar-version "1.5.0")

;; Define a variable to store camel language server jar name
(defconst lsp-camel-jar-name (format "camel-lsp-server-%s.jar" lsp-camel-jar-version))

;; Directory in which the servers will be installed. Lsp Server Install Dir: /home/npr/.emacs.d/.cache/camells/camel-lsp-server-1.5.0.jar
(defcustom lsp-camel-jar-file (f-join lsp-server-install-dir "camells" lsp-camel-jar-name)
  "Camel Language server jar command."
  :type 'string
  :group 'lsp-camel
  :type 'file
  :package-version '(lsp-mode . "8.0.0"))

(defcustom lsp-camel-jar-download-url
  (format "https://repo1.maven.org/maven2/com/github/camel-tooling/camel-lsp-server/%s/%s" lsp-camel-jar-version lsp-camel-jar-name)
  "Automatic download url for lsp-camel."
  :type 'string
  :group 'lsp-camel
  :package-version '(lsp-mode . "8.0.0"))

(lsp-dependency
 'camells
 '(:system lsp-camel-jar-file)
 `(:download :url lsp-camel-jar-download-url
             :store-path lsp-camel-jar-file))

(defcustom lsp-camel-server-command `("java" "-jar" , lsp-camel-jar-file)
  "Camel server command."
  :type '(repeat string)
  :group 'lsp-camel
  :package-version '(lsp-mode . "8.0.0"))

(defun lsp-camel--create-connection ()
  (lsp-stdio-connection
   (lambda () lsp-camel-server-command)
   (lambda () (f-exists? lsp-camel-jar-file))))

(lsp-register-client
 (make-lsp-client :new-connection (lsp-camel--create-connection)
                  :activation-fn (lsp-activate-on "xml")
                  :priority 0
                  :server-id 'camells
                  :add-on? t
                  :multi-root t
                  :initialized-fn (lambda (workspace)
                                    (with-lsp-workspace workspace
                                      (lsp--set-configuration (lsp-configuration-section "camel"))))
                  :download-server-fn (lambda (_client callback error-callback _update?)
                                        (lsp-package-ensure 'camells callback error-callback))))

(lsp-consistency-check lsp-camel)

(provide 'lsp-camel)
;;; lsp-camel.el ends here
```
- Openign the lsp-camel.el file
- Evaluating it by calling M-x eval-buffer
- Loading Camel LS by calling: M-x lsp-install-server and choosing camells
- Opening a camel.xml file with this kind of content:
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
       http://camel.apache.org/schema/spring https://camel.apache.org/schema/spring/camel-spring.xsd">

  <camelContext id="camel" xmlns="http://camel.apache.org/schema/spring">
    <route id="a route">
      <from uri="timer:timerName?delay=1000&amp;exchangePattern=InvalidEnumValue"/>
      <to uri="direct:drink"/>
    </route>
  </camelContext>
</beans>
```
- I can notice the validation error provided by the Camel LS:
![Screenshot from 2022-05-31 16-20-28](https://user-images.githubusercontent.com/1105127/171196317-5c4897f6-e5b3-4861-a627-7f03885a4668.png)

sidenote: I'm unable to have completion for xml or Camel or anythign else in the emacs editor. I guess that I just do not know how to trigger it.

**Comment by Navyashree0923** [comment]
Hello @yyoncho I have created a file `lsp-camel.el`. I have placed this file under "~/.emacs.d/elpa/lsp-mode-8.0.0".

This is the content my `lsp-camel.el` file.

```

;;; lsp-camel.el --- LSP Camel server integration        -*- lexical-binding: t; -*-


;;; Code:

(require 'lsp-mode)

(defgroup lsp-camel nil
 "LSP support for Camel, using camel-language-server"
 :group 'lsp-mode
 :tag "Language Server"
 :package-version '(lsp-mode . "8.0.0"))

;; Define a variable to store camel language server jar version
(defconst lsp-camel-jar-version "1.5.0")

;; Define a variable to store camel language server jar name
(defconst lsp-camel-jar-name (format "camel-lsp-server-%s.jar" lsp-camel-jar-version))

;; Directory in which the servers will be installed. Lsp Server Install Dir: ~/.emacs.d/.cache/camells
(defcustom lsp-camel-jar-file (f-join lsp-server-install-dir "camells" lsp-camel-jar-name)
 "Camel Language server jar command."
 :type 'string
 :group 'lsp-camel
 :type 'file
 :package-version '(lsp-mode . "8.0.0"))

(defcustom lsp-camel-jar-download-url
 (format "https://repo1.maven.org/maven2/com/github/camel-tooling/camel-lsp-server/%s/%s" lsp-camel-jar-version lsp-camel-jar-name)
 "Automatic download url for lsp-camel."
 :type 'string
 :group 'lsp-camel
 :package-version '(lsp-mode . "8.0.0"))

(lsp-dependency
'camells
'(:system lsp-camel-jar-file)
`(:download :url lsp-camel-jar-download-url
            :store-path lsp-camel-jar-file))

(defcustom lsp-camel-server-command `("java" "-jar" , lsp-camel-jar-file)
 "Camel server command."
 :type '(repeat string)
 :group 'lsp-camel
 :package-version '(lsp-mode . "8.0.0"))

(defun lsp-camel--create-connection ()
 (lsp-stdio-connection
  (lambda () lsp-camel-server-command)
  (lambda () (f-exists? lsp-camel-jar-file))))

(lsp-register-client
(make-lsp-client :new-connection (lsp-camel--create-connection)
                 :activation-fn (lsp-activate-on "xml" "java" "spring-boot-properties-yaml")
                 :priority 0
                 :server-id 'camells 
                 :add-on? t
                 :multi-root t
                 :initialized-fn (lambda (workspace)
                                   (with-lsp-workspace workspace
                                     (lsp--set-configuration (lsp-configuration-section "camel"))))
                 :download-server-fn (lambda (_client callback error-callback _update?)
                                       (lsp-package-ensure 'camells callback error-callback))))

(lsp-consistency-check lsp-camel)

(provide 'lsp-camel)
;;; lsp-camel.el ends here
```
I have created `init.el` file. 

This is the content my `init.el` file.

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(yaml java-imports lsp-mode)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(setq auto-mode-alist
    (cons '("\\.yaml$" . yaml-mode) auto-mode-alist))
 
(require 'lsp-mode)
(add-hook 'nxml-mode-hook #'lsp)

 (require 'lsp-mode)
(add-hook 'java-mode-hook #'lsp)

(require 'lsp-mode)
(add-hook 'yaml-mode-hook #'lsp)
```
I was able to successfully provide Text Editing capabilities of Camel URI with Camel JAVA and XML. But I'm trying for Yaml with the above mentioned files. I'm not able to see any editing capabilities for Yaml. 

Please is there any sequence of steps that I should follow in order to achieve this task?
