### ISSUE TITLE
omnisharp: error when typing method return type

### ISSUE THREAD

**Issue by sollidsnake** [emacs-lsp/lsp-mode#3908]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Using omnisharp lsp backend for C#, when I try to type a method name, lsp package throws an error and doesn't show any suggestion.

### Steps to reproduce

1. Create a new project with `dotnet new classlib`.
2. Open Class1.cs
3. Make sure you are using omnisharp backend
4. Start typing a method like: "public s`|`". When the cursor is positioned in place of `|`, it throws the error showed above.

My OS is Arch Linux. I tried omnisharp in vscode and neovim and worked as expected, so I think it's related to this package. I also tried `csharp-ls` in Emacs backend which also worked.

### Expected behavior

Show the existing types suggestions of throwing error.

### Which Language Server did you use?

lsp omnisharp

### OS

Linux

### Error callstack

```emacs-lisp
[Trace - 11:18:30 PM] Sending request 'textDocument/documentHighlight - (236)'.
Params: {
  "textDocument": {
    "uri": "file:///home/jesse/code/testproject/Class1.cs"
  },
  "position": {
    "line": 4,
    "character": 14
  }
}


[Trace - 11:18:30 PM] Received notification 'window/logMessage'.
Params: {
  "type": 2,
  "message": "OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService: No symbol found. File: /home/jesse/code/testproject/Class1.cs, Line: 4, Column: 14. | "
}


[Trace - 11:18:30 PM] Received response 'textDocument/documentHighlight - (236)' in 7ms.
Result: []


[Trace - 11:18:30 PM] Received response 'textDocument/codeAction - (235)' in 8ms.
Result: []

--------------------------------------

OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker: Failed to handle request textDocument/completion 412 - System.InvalidOperationException: Unexpected null - line 226
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber)
   at Microsoft.CodeAnalysis.Snippets.AbstractSnippetProvider.AnnotateNodesToReformatAsync(Document document, SyntaxAnnotation findSnippetAnnotation, SyntaxAnnotation cursorAnnotation, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Snippets.AbstractSnippetProvider.AddFormatAnnotationAsync(Document document, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Snippets.AbstractSnippetProvider.GetSnippetAsync(Document document, Int32 position, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.Providers.Snippets.AbstractSnippetCompletionProvider.GetChangeAsync(Document document, CompletionItem item, Nullable`1 commitKey, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.CompletionService.GetChangeAsync(Document document, CompletionItem item, Nullable`1 commitCharacter, CancellationToken cancellationToken)
   at OmniSharp.Roslyn.CSharp.Services.Completion.CompletionListBuilder.BuildCompletionItemsSync(Document document, SourceText sourceText, Int64 cacheId, Int32 position, CompletionService completionService, CompletionList completions, TextSpan typedSpan, Boolean expectingImportedItems, Boolean isSuggestionMode) in /home/vsts/work/1/s/src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionListBuilder_Sync.cs:line 125
   at OmniSharp.Roslyn.CSharp.Services.Completion.CompletionListBuilder.BuildCompletionItems(Document document, SourceText sourceText, Int64 cacheId, Int32 position, CompletionService completionService, CompletionList completions, TextSpan typedSpan, Boolean expectingImportedItems, Boolean isSuggestionMode, Boolean enableAsyncCompletion) in /home/vsts/work/1/s/src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionListBuilder.cs:line 80
   at OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService.Handle(CompletionRequest request, Boolean forceExpandedCompletionIndexCreation) in /home/vsts/work/1/s/src/OmniSharp.Roslyn.CSharp/Services/Completion/CompletionService.cs:line 154
   at OmniSharp.LanguageServerProtocol.Handlers.OmniSharpCompletionHandler.Handle(CompletionParams request, CancellationToken token) in /home/vsts/work/1/s/src/OmniSharp.LanguageServerProtocol/Handlers/OmniSharpCompletionHandler.cs:line 72
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext() | Method='textDocument/completion' RequestId='412'
```

**Comment by ericdallo** [comment]
It seems to be that exception comes from server @sollidsnake, maybe open the issue there?

**Comment by sollidsnake** [comment]
@ericdallo Since it works on neovim and vscode, I thought it was related to how lsp-mode talks to the server? Or that doesn't make sens?

**Comment by ericdallo** [comment]
Yes, it's a correct thought usually, but since it's a server exception or server is handling something differently or emacs side is missing some config to pass to server, even so, an exception on server looks wrong to me, they should know why that is happening probably

**Comment by sollidsnake** [comment]
I'm not having this issue anymore. Seems to have been fixed either by omnisharp or lsp-mode, so I think it can be closed
