### ISSUE TITLE
Error With Python LSP Server Progress Reporting

### ISSUE THREAD

**Issue by kevinjfoley** [emacs-lsp/lsp-mode#4367]
### Thank you for the bug report

- [X] I am using the latest version of `lsp-mode` related packages.
- [X] I checked [FAQ](https://emacs-lsp.github.io/lsp-mode/page/faq/) and [Troubleshooting](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/) sections
- [ ] You may also try reproduce the issue using clean environment using the following command: `M-x lsp-start-plain`

### Bug description

Python files take a long time to open, about 3-4 seconds.  Looking in `pylsp::stderr`, I see:
```
WARNING - pylsp.workspace - There was an error while trying to initialize progress reporting.Likely progress reporting was used in a synchronous LSP handler, which is not supported by progress reporting yet. To prevent waiting for the timeout you can set `skip_token_initialization=True`. Not every editor will show progress then, but many will.
Traceback (most recent call last):
  File "/Users/kfoley/.pyenv/versions/3.8.16/envs/venv/lib/python3.8/site-packages/pylsp/workspace.py", line 250, in _progress_begin
    self._endpoint.request(
  File "/Users/kfoley/.pyenv/versions/3.8.16/lib/python3.8/concurrent/futures/_base.py", line 446, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
```

The timestamps seem to match up with when the file actual opens and so it seems like this is keeping the file from appearing until it has timed out.

### Steps to reproduce

Open a python file with the Python LSP Server.

### Expected behavior

No timeout error from lsp server

### Which Language Server did you use?

Using latest version of [Python LSP Server](https://github.com/python-lsp/python-lsp-server)

### OS

MacOS

**Comment by jcs090218** [comment]
I am not sure what's the correct fix. Let me ping one of our Python maintainers. 

cc @seagle0128

**Comment by ZedThree** [comment]
I see the exact same message during auto-completion, with a similar several second wait. This is with `python-lsp-server==1.11.0`
