### ISSUE TITLE
Error with Rust LS: 'Could not convert URI to path'

### ISSUE THREAD

**Issue by gpanders** [emacs-lsp/lsp-mode#624]
**Describe the bug**
Rust LS crashes with the following error:
```
Thread 'main' panicked at 'Could not convert URI to path: ()', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'Could not convert URI to path: ()', src/libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Process rls stderr<1> finished

Process rls stderr finished
```

**To Reproduce**
1. Install most recent lsp-mode from MELPA
2. Enable `lsp` in `rust-mode`

**Expected behavior**
Language server should not crash.

**Which Language Server did you use**
Rust (rls)

```bash
$ rls --version
rls-preview 1.31.6 (bfa1371 2018-12-07)
```

**OS**
macOS High Sierra 

**Error callstack**
If there is an error please reproduce the issue with `toggle-debug-on-error` and after setting `lsp-print-io` to t, and then include the callstack and attach the content of \*Messages\* buffer.

``` emacs-lisp
Debugger entered--Lisp error: (error "rls: Cannot communicate with the process (exit)")
  signal(error ("rls: Cannot communicate with the process (exit)"))
  error("%s: Cannot communicate with the process (%s)" "rls" exit)
  lsp--send-no-wait("Content-Length: 69\015\n\015\n{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"initialized\",\n  \"params\": {\n  }\n}\n" #<process rls>)
  #f(compiled-function (it) #<bytecode 0x4156bef1>)(#s(lsp--workspace :parser #s(lsp--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "" :queued-notifications nil :queued-requests nil :workspace #1) :file-versions #<hash-table equal 0/65 0x4155beb9> :server-capabilities #<hash-table equal 15/65 0x4156c2d5> :registered-server-capabilities nil :root "~/Projects/rust/minigrep/" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x43cbdc1d>) :test\? #f(compiled-function () #<bytecode 0x43cbdc35>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 1/65 0x43cbdc41> :request-handlers #<hash-table equal 0/65 0x43cbe739> :response-handlers #<hash-table eql 3/65 0x43cbea31> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x43cbed29> :action-handlers #<hash-table equal 0/65 0x43cbf001> :use-native-json nil :major-modes (rust-mode rustic-mode) :activation-fn nil :priority -1 :server-id rls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil) :host-root nil :proc #<process rls> :cmd-proc #<process rls> :buffers (#<buffer lib.rs>) :highlight-overlays #<hash-table eq 0/65 0x4155bed9> :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x4155deb5> :watches #<hash-table equal 0/65 0x4155ded5> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x4155f2b5>))
  mapcar(#f(compiled-function (it) #<bytecode 0x4156bef1>) (#s(lsp--workspace :parser #s(lsp--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "" :queued-notifications nil :queued-requests nil :workspace #2) :file-versions #<hash-table equal 0/65 0x4155beb9> :server-capabilities #<hash-table equal 15/65 0x4156c2d5> :registered-server-capabilities nil :root "~/Projects/rust/minigrep/" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x43cbdc1d>) :test\? #f(compiled-function () #<bytecode 0x43cbdc35>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 1/65 0x43cbdc41> :request-handlers #<hash-table equal 0/65 0x43cbe739> :response-handlers #<hash-table eql 3/65 0x43cbea31> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x43cbed29> :action-handlers #<hash-table equal 0/65 0x43cbf001> :use-native-json nil :major-modes (rust-mode rustic-mode) :activation-fn nil :priority -1 :server-id rls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil) :host-root nil :proc #<process rls> :cmd-proc #<process rls> :buffers (#<buffer lib.rs>) :highlight-overlays #<hash-table eq 0/65 0x4155bed9> :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x4155deb5> :watches #<hash-table equal 0/65 0x4155ded5> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x4155f2b5>)))
  lsp--send-notification((:jsonrpc "2.0" :method "initialized" :params #<hash-table eql 0/65 0x4156f2d5>))
  lsp-notify("initialized" #<hash-table eql 0/65 0x4156f2d5>)
  #f(compiled-function (response) #<bytecode 0x4155d2e9>)(#<hash-table equal 1/65 0x4156c2b5>)
  #f(compiled-function (result) #<bytecode 0x4155f6c5>)(#<hash-table equal 1/65 0x4156c2b5>)
  lsp--parser-on-message(#s(lsp--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "" :queued-notifications nil :queued-requests nil :workspace #s(lsp--workspace :parser #1 :file-versions #<hash-table equal 0/65 0x4155beb9> :server-capabilities #<hash-table equal 15/65 0x4156c2d5> :registered-server-capabilities nil :root "~/Projects/rust/minigrep/" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name) #<bytecode 0x43cbdc1d>) :test\? #f(compiled-function () #<bytecode 0x43cbdc35>)) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 1/65 0x43cbdc41> :request-handlers #<hash-table equal 0/65 0x43cbe739> :response-handlers #<hash-table eql 3/65 0x43cbea31> :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x43cbed29> :action-handlers #<hash-table equal 0/65 0x43cbf001> :use-native-json nil :major-modes (rust-mode rustic-mode) :activation-fn nil :priority -1 :server-id rls :multi-root nil :initialization-options nil :library-folders-fn nil :before-file-open-fn nil :initialized-fn nil :remote? nil) :host-root nil :proc #<process rls> :cmd-proc #<process rls> :buffers (#<buffer lib.rs>) :highlight-overlays #<hash-table eq 0/65 0x4155bed9> :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x4155deb5> :watches #<hash-table equal 0/65 0x4155ded5> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 0/65 0x4155f2b5>)) "{\"jsonrpc\":\"2.0\",\"id\":3,\"result\":{\"capabilities\":{\"textDocumentSync\":2,\"hoverProvider\":true,\"completionProvider\":{\"resolveProvider\":true,\"triggerCharacters\":[\".\",\":\"]},\"definitionProvider\":true,\"implementationProvider\":true,\"referencesProvider\":true,\"documentHighlightProvider\":true,\"documentSymbolProvider\":true,\"workspaceSymbolProvider\":true,\"codeActionProvider\":true,\"codeLensProvider\":{\"resolveProvider\":false},\"documentFormattingProvider\":true,\"documentRangeFormattingProvider\":false,\"renameProvider\":true,\"executeCommandProvider\":{\"commands\":[\"rls.applySuggestion-24091\",\"rls.deglobImports-24091\"]}}}}")
  #f(compiled-function (proc output) #<bytecode 0x4155eae9>)(#<process rls> "Content-Length: 607\015\n\015\n{\"jsonrpc\":\"2.0\",\"id\":3,\"result\":{\"capabilities\":{\"textDocumentSync\":2,\"hoverProvider\":true,\"completionProvider\":{\"resolveProvider\":true,\"triggerCharacters\":[\".\",\":\"]},\"definitionProvider\":true,\"implementationProvider\":true,\"referencesProvider\":true,\"documentHighlightProvider\":true,\"documentSymbolProvider\":true,\"workspaceSymbolProvider\":true,\"codeActionProvider\":true,\"codeLensProvider\":{\"resolveProvider\":false},\"documentFormattingProvider\":true,\"documentRangeFormattingProvider\":false,\"renameProvider\":true,\"executeCommandProvider\":{\"commands\":[\"rls.applySuggestion-24091\",\"rls.deglobImports-24091\"]}}}}")
```

**Notes**
I do not believe the issue is with `rls` itself because it works fine inside of Vim.

Googling the error message shows other [Github issues](https://github.com/rust-lang/rls/issues/1173) relating to the VS Code extension, which further implies that the issue is with the client (in this case, `lsp-mode`) and not the server.

**Comment by yyoncho** [comment]
Can you do `(setq lsp-print-io t)` and post the output of \*lsp-log\*?

**Comment by yyoncho** [comment]
I just upgraded RLS on my machine and tested with hello world project and it does not reproduce out of the box on linux mint. Can you verify that you have picked the proper root (use lsp-describe-session to find the roots). Can you also check what is the exact command that vim us running? Lsp is starting rls without any arguments.

**Comment by gpanders** [comment]
`lsp-describe-session` shows a buffer with
```
[X] ~/Projects/rust/minigrep/
```
which is the correct project root (it contains the `Cargo.toml` file).

I'm not totally sure how it's started in Vim. I use [coc.nvim's rls plugin](https://github.com/neoclide/coc-rls) which is written in Typescript. As best as I can tell it is started using `rustup run stable rls`.

`*lsp-log*`:
```
>>> rls:68858 status:starting(async)
Content-Length: 1921

{
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "processId": 57156,
    "rootPath": "/Users/greande/Projects/rust/minigrep/",
    "rootUri": "file://~/Projects/rust/minigrep/",
    "capabilities": {
      "workspace": {
        "applyEdit": true,
        "executeCommand": {
          "dynamicRegistration": false
        },
        "workspaceFolders": true
      },
      "textDocument": {
        "declaration": {
          "linkSupport": true
        },
        "definition": {
          "linkSupport": true
        },
        "implementation": {
          "linkSupport": true
        },
        "typeDefinition": {
          "linkSupport": true
        },
        "synchronization": {
          "willSave": true,
          "didSave": true,
          "willSaveWaitUntil": true
        },
        "documentSymbol": {
          "symbolKind": {
            "valueSet": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25
            ]
          },
          "hierarchicalDocumentSymbolSupport": true
        },
        "formatting": {
          "dynamicRegistration": true
        },
        "codeAction": {
          "dynamicRegistration": true
        },
        "completion": {
          "completionItem": {
            "snippetSupport": true
          }
        },
        "signatureHelp": {
          "signatureInformation": {
            "parameterInformation": {
              "labelOffsetSupport": true
            }
          }
        }
      }
    },
    "initializationOptions": null
  },
  "id": 2
}

<<<< rls:68858 status:starting
{
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "capabilities": {
      "textDocumentSync": 2,
      "hoverProvider": true,
      "completionProvider": {
        "resolveProvider": true,
        "triggerCharacters": [
          ".",
          ":"
        ]
      },
      "definitionProvider": true,
      "implementationProvider": true,
      "referencesProvider": true,
      "documentHighlightProvider": true,
      "documentSymbolProvider": true,
      "workspaceSymbolProvider": true,
      "codeActionProvider": true,
      "codeLensProvider": {
        "resolveProvider": false
      },
      "documentFormattingProvider": true,
      "documentRangeFormattingProvider": false,
      "renameProvider": true,
      "executeCommandProvider": {
        "commands": [
          "rls.applySuggestion-68858",
          "rls.deglobImports-68858"
        ]
      }
    }
  }
}
>>> rls:68858(async)
Content-Length: 69

{
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {
  }
}

>>> rls:68862 status:starting(async)
Content-Length: 1921

{
  "jsonrpc": "2.0",
  "method": "initialize",
  "params": {
    "processId": 57156,
    "rootPath": "/Users/greande/Projects/rust/minigrep/",
    "rootUri": "file://~/Projects/rust/minigrep/",
    "capabilities": {
      "workspace": {
        "applyEdit": true,
        "executeCommand": {
          "dynamicRegistration": false
        },
        "workspaceFolders": true
      },
      "textDocument": {
        "declaration": {
          "linkSupport": true
        },
        "definition": {
          "linkSupport": true
        },
        "implementation": {
          "linkSupport": true
        },
        "typeDefinition": {
          "linkSupport": true
        },
        "synchronization": {
          "willSave": true,
          "didSave": true,
          "willSaveWaitUntil": true
        },
        "documentSymbol": {
          "symbolKind": {
            "valueSet": [
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              23,
              24,
              25
            ]
          },
          "hierarchicalDocumentSymbolSupport": true
        },
        "formatting": {
          "dynamicRegistration": true
        },
        "codeAction": {
          "dynamicRegistration": true
        },
        "completion": {
          "completionItem": {
            "snippetSupport": true
          }
        },
        "signatureHelp": {
          "signatureInformation": {
            "parameterInformation": {
              "labelOffsetSupport": true
            }
          }
        }
      }
    },
    "initializationOptions": null
  },
  "id": 3
}

<<<< rls:68862 status:starting
{
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "capabilities": {
      "textDocumentSync": 2,
      "hoverProvider": true,
      "completionProvider": {
        "resolveProvider": true,
        "triggerCharacters": [
          ".",
          ":"
        ]
      },
      "definitionProvider": true,
      "implementationProvider": true,
      "referencesProvider": true,
      "documentHighlightProvider": true,
      "documentSymbolProvider": true,
      "workspaceSymbolProvider": true,
      "codeActionProvider": true,
      "codeLensProvider": {
        "resolveProvider": false
      },
      "documentFormattingProvider": true,
      "documentRangeFormattingProvider": false,
      "renameProvider": true,
      "executeCommandProvider": {
        "commands": [
          "rls.applySuggestion-68862",
          "rls.deglobImports-68862"
        ]
      }
    }
  }
}
>>> rls:68862(async)
Content-Length: 69

{
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {
  }
}
```

**Comment by yyoncho** [comment]
Probably this will fix the issue: 

```
(defun lsp--path-to-uri (path)
  "Convert PATH to a uri."
  (concat lsp--uri-file-prefix
          (url-hexify-string (expand-file-name (or (file-remote-p path 'localname t) path))
                             url-path-allowed-chars)))
```

I will do more testing tomorrow morning my time.

**Comment by yyoncho** [comment]
Pushed the change - https://github.com/emacs-lsp/lsp-mode/commit/e0a66058ad938be6a532352fb3a42f5867a4d195 , can you retest?

**Comment by gpanders** [comment]
Seems to work now!

**Comment by yyoncho** [comment]
@gpanders can you do a comparison between coc.nvim and `lsp-mode` stressing on the things that you think that could be improved in `lsp-mode` (apart from this issue) or you do not like?
