### ISSUE TITLE
ocaml lsp seems broken

### ISSUE THREAD

**Issue by kkhan01** [emacs-lsp/lsp-mode#953]
**Describe the bug**
`ocaml-language-server` does not work. 

**To Reproduce**
Here is my config--
```lisp
  (use-package lsp-mode
    :bind
    (:map lsp-mode-map
          ("C-c d" . lsp-find-definition)
          ("C-c e" . lsp-rename)
          ("C-c f" . lsp-format-buffer))
    :custom
    (lsp-auto-guess-root t)
    (lsp-before-save-edits t)
    (lsp-enable-indentation t)
    (lsp-auto-configure nil)
    (lsp-enable-snippet nil)
    (lsp-prefer-flymake nil)
    :config
    (add-to-list 'lsp-language-id-configuration '(python-mode . "python"))
    (add-to-list 'lsp-language-id-configuration '(caml-mode . "ocaml"))
    (add-to-list 'lsp-language-id-configuration '(tuareg-mode . "ocaml"))
    (add-to-list 'lsp-language-id-configuration '(reason-mode . "ocaml"))

    (lsp-register-client
     (make-lsp-client :new-connection (lsp-stdio-connection "pyls")
                      :major-modes '(python-mode)
                      :server-id 'pyls))

    (lsp-register-client
     (make-lsp-client :new-connection (lsp-stdio-connection "ocaml-language-server")
                      :major-modes '(caml-mode tuareg-mode reason-mode)
                      :server-id 'ocamlmerlin-lsp))

    (setq lsp-print-io t))

  (use-package lsp-ui
    :after (lsp-mode)
    :hook
    (lsp-mode . lsp-ui-mode)
    :bind
    (:map lsp-mode-map
          ("C-c C-j" . lsp-ui-imenu)
          ("C-c l" . lsp-ui-flycheck-list)
          ("C-c r" . lsp-ui-peek-find-references)
          ("C-c t" . lsp-find-type-definition)
          ([remap xref-find-definitions] . lsp-ui-peek-find-definitions)
          ([remap xref-find-references] . lsp-ui-peek-find-references))
    :custom
    (lsp-ui-flycheck-enable t))

  (use-package company-lsp
    :after (company lsp-mode)
    :bind
    (:map lsp-mode-map
          ("C-/" . company-lsp))
    :custom
    (company-lsp-async t)
    (company-lsp-cache-candidates t)
    (company-lsp-enable-snippets nil)
    (company-lsp-enable-recompletion t)
    :config
    (add-to-list 'company-backends #'company-lsp))


  (use-package tuareg
    :if (executable-find "ocaml")
    :after (lsp)
    :hook
    (tuareg-mode . lsp)
    :mode
    (("\\.ml[ip]?\\'" . tuareg-mode)
     ("\\.mly\\'" . tuareg-menhir-mode)
     ("[./]opam_?\\'" . tuareg-opam-mode)
     ("\\(?:\\`\\|/\\)jbuild\\(?:\\.inc\\)?\\'" . tuareg-jbuild-mode)
     ("\\.eliomi?\\'" . tuareg-mode))
    :custom
    (tuareg-match-patterns-aligned t)
    (tuareg-indent-align-with-first-arg t))
```

I also tried replacing `"ocaml-language-server"` in new connection to `""ocaml-language-server" --stdio "`. This gives me the error `LSP :: No LSP server for tuareg-mode(check *lsp-log*).`. This results in just giving me syntax highlighting, with nothing else. 

**Expected behavior**
The server should start up normally.

**Which Language Server did you use**
ocaml-language-server

**OS**
Which os do you use?
 Manjaro 18.0.4 Illyria
**Error callstack**
- This is without `--stdio`:
`*lsp-log*`
```
Command "ocaml-language-server" is present on the path.
Found the following clients for /home/shan/Projects/ocamlisp-lipcrepl/src/main.ml: (server-id ocamlmerlin-lsp, priority 0)
The following clients were selected based on priority: (server-id ocamlmerlin-lsp, priority 0)
Command "ocaml-language-server" is present on the path.
Found the following clients for /home/shan/Projects/ocamlisp-lipcrepl/src/main.ml: (server-id ocamlmerlin-lsp, priority 0)
The following clients were selected based on priority: (server-id ocamlmerlin-lsp, priority 0)
Command "ocaml-language-server" is present on the path.
Found the following clients for /home/shan/Projects/ocamlisp-lipcrepl/src/main.ml: (server-id ocamlmerlin-lsp, priority 0)
The following clients were selected based on priority: (server-id ocamlmerlin-lsp, priority 0)
```

`*ocamlmerlin-lsp*`
blank buffer

`*ocamlmerlin-lsp::stderr*`
```
Process ocamlmerlin-lsp stderr<1> finished

Process ocamlmerlin-lsp stderr finished
/home/shan/.nvm/versions/node/v12.1.0/lib/node_modules/ocaml-language-server/node_modules/vscode-languageserver/lib/main.js:696
        throw new Error("Connection input stream is not set. " + commandLineMessage);
        ^

Error: Connection input stream is not set. Use arguments of createConnection or set command line parameters: '--node-ipc', '--stdio' or '--socket={number}'
    at _createConnection (/home/shan/.nvm/versions/node/v12.1.0/lib/node_modules/ocaml-language-server/node_modules/vscode-languageserver/lib/main.js:696:15)
    at Object.createConnection (/home/shan/.nvm/versions/node/v12.1.0/lib/node_modules/ocaml-language-server/node_modules/vscode-languageserver/lib/main.js:643:12)
    at new Session (/home/shan/.nvm/versions/node/v12.1.0/lib/node_modules/ocaml-language-server/bin/server/session/index.js:24:34)
    at Object.<anonymous> (/home/shan/.nvm/versions/node/v12.1.0/lib/node_modules/ocaml-language-server/bin/server/index.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
    at internal/main/run_main_module.js:17:11

Process ocamlmerlin-lsp stderr finished
```

One of the `*lsp-log: ocamlmerlin-lsp:13948*`
```
[Trace - 12:31:29 PM] Sending request 'initialize - (1)'.
Params: {
  "processId": 13885,
  "rootPath": "/home/shan/Projects/ocamlisp-lipcrepl/",
  "rootUri": "file:///home/shan/Projects/ocamlisp-lipcrepl/",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "codeAction": {
        "dynamicRegistration": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        }
      },
      "completion": {
        "completionItem": {
          "snippetSupport": false,
          "documentationFormat": [
            "markdown"
          ]
        },
        "contextSupport": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "documentLink": {
        "dynamicRegistration": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "foldingRange": {
        "dynamicRegistration": true,
        "rangeLimit": null,
        "lineFoldingOnly": null
      }
    }
  },
  "initializationOptions": null
}
```

- This is with `--stdio`:
`*lsp-log*`
```
Command "ocaml-language-server --stdio" is not present on the path.
```

**Comment by yyoncho** [comment]
Can you set the command to list `'("ocaml-language-server" "--stdio")`?

**Comment by kkhan01** [comment]
That works perfectly, thanks.
